### ISSUE TITLE
Get Glimpse Website is Down

### ISSUE THREAD

**Issue by LancerOfTruth** [Glimpse/Glimpse#1017]
The website [http://getglimpse.com/](http://getglimpse.com/ ) throws a "404 Web Site not found" error.

**Comment by devbrsa** [comment]
It seems Glimpse was abandoned or left behind.

**Comment by Tridus** [comment]
It appears to have been doing that for over a month. So yes, sadly it appears that the project may have been abandoned. :(

**Comment by multco-malan** [comment]
And it continues to be down on 12/21/2018.
With all of the "embedded" links to getglimpse.com this is a bit disconcerting.

**Comment by alindgren** [comment]
It now redirects to https://github.com/glimpse/glimpse

**Comment by seangwright** [comment]
The code that makes the check can be found here https://github.com/Glimpse/Glimpse/blob/97ac70d297609f6799e40231f8f1c50db995e2d0/source/Glimpse.Core/Resource/VersionCheckResource.cs#L91

You could set the `GlimpseVersionCheckAPIDomain` app setting key to a domain you control and handle the requests to `/Api/Version/Check`.

That said, the request is cached for a day, so if you aren't restarting the site, you shouldn't see a ton of requests.
