### ISSUE TITLE
Consider basing off PhotoGIMP

### ISSUE THREAD

**Issue by probonopd** [Glimpse/Glimpse#1026]
Consider basing off [PhotoGIMP](https://github.com/sudo-give-me-coffee/PhotoGIMP). It addresses the GUI quirks that have been criticized in the GNU Image Manipulation Program for a long time, and makes it easier to operate for users coming from other image manipulation applications.

**Comment by maxtron95** [comment]
@probonopd This is the wrong Glimpse. This Glimpse is a diagnostics platform, not an image editor. The Glimpse you were probably looking for is here: https://github.com/glimpse-editor/Glimpse

**Comment by probonopd** [comment]
Sorry. Indeed.
