### ISSUE TITLE
Glimpse affected by GIMP fatal bug.

### ISSUE THREAD

**Issue by vanKaam** [Glimpse/Glimpse#1032]
The bug is the nefarious crash on export/preference bug.

I never had an issue with this in GIMP 2.10.8 then when I installed 2.10.14 a few days ago it started happening to me, but even more when I uninstall 2.10.14 and reinstall 2.10.8 the latter doesn't even load, but crashes as soon as it tries to open.

Afterwards I only got 2.10.8 to work again by manually deleting all GIMP files I could find, .gimp-2.8, the GIMP folder in AppData/Roaming, and all GIMP, GeGL, Babl, gtk data in AppData/Local, so it starts right now, but it now also produces the same fatal error while proceeding to edit->preferences, while before it wouldn't!

Also exporting images fails right now, this is quite an evil bug

This bug is so pervasive that even after uninstalling GIMP, and deleting all files in AppData, that when I installed GLIMPSE it makes even GLIMPSE crash with the same bug edit->preferences, but it made GLIMPSE crash even while creating a new canvas.

Note: 2.8 installs and works fine for me, except it doesn't open my recently created projects because the XCF file is too new.

2\.10.8 was working nice for me, then 2.10.14 installed something which messed up a file which even GLIMPSE uses, so now none of these programs are working, so I would like to request an uninstall that gives the option to reverse all that it installed, which is considered the right of the user that any company promoting openness and transparency should uphold.

But now I'm left with a rogue file or folder messing up my program, with no proper solution except deleting all windows files and installing windows anew. 
Some people might think this is a small thing, but I use GIMP/Glimpse because they are freeware, I don't want to use software without the consent of it's owner, which include Windows. So it means I have to go find someone willing to share his license with me so I can reinstall windows again legally.

So plz just give me the ability to delete all that it installed, even if it where to be in a "Advanced" section.

Thx in advance.

**Comment by vanKaam** [comment]
Update:
My computer is running Windows 7 32 bits on a Intel Core i5 laptop with onboard Intel HD Graphics 3000.

One of the other GIMP users that had the edit->preferences bug was also running it on Windows 32 bit, then when he installed Windows 64 bit on the same computer he didn't experience a problem.
(The other user's comment can be found over [here](https://gitlab.gnome.org/GNOME/gimp/issues/2846#note_507083))

**Comment by maxtron95** [comment]
@vanKaam FYI, this is the wrong Glimpse (diagnostics platform). The Glimpse that you are probably looking for is: https://github.com/glimpse-editor/Glimpse

**Comment by vanKaam** [comment]
> @vanKaam FYI, this is the wrong Glimpse (diagnostics platform). The Glimpse that you are probably looking for is: https://github.com/glimpse-editor/Glimpse
Thx
