### ISSUE TITLE
Need an easy to use "Save for Web" option

### ISSUE THREAD

**Issue by cafeTechne** [Glimpse/Glimpse#1033]
An easy to use "save for web" option under File would be very useful. What would it take to implement something like this?

**Comment by maxtron95** [comment]
@cafeTechne About that, are you referring to this Glimpse?

![ksnip_20200505-114814](https://user-images.githubusercontent.com/53346722/81092963-044cce80-8ec7-11ea-9bc4-4aab835e25a5.png)

If so, then this is the wrong repo and the link to that Glimpse is here (https://github.com/glimpse-editor/Glimpse)

**Comment by cafeTechne** [comment]
So sorry! How embarassing!
