### ISSUE TITLE
Could not load file or assembly Microsoft.Web.Infrastructure

### ISSUE THREAD

**Issue by matt-richardson** [Glimpse/Glimpse#173]
Similar to issue #92, I'm getting the following error in the Request tab.

Could not load file or assembly 'Microsoft.Web.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

This is on a web forms project, on a machine that doesn't have mvc3 installed.

I'm resolving by installing mvc3, but it may be worth considering an alternative mechanism to retrieve the information for this tab.

**Comment by superdev810** [comment]
I got this issue in the IIS cloud.
It works in my local.
What is the problem?
