### ISSUE TITLE
Could Not Load Module Error

### ISSUE THREAD

**Issue by NickSchweitzer** [Glimpse/Glimpse#221]
I have an existing ASP.NET Web Forms app which I'm trying to add Glimpse to. I ran the following NuGet package command as it says in the Quick Start on the website.

"Install-Package Glimpse -Pre"

And all it did was add a reference to my project references, but did not make any modifications to my web.config. I manually added the appropriate Module and Handler methods, but I now get the following error:

Could not load type 'Glimpse.Core.Module' from assembly 'Glimpse.Core'.

When I look at the Object Browser and look at the Glimpse.Core namespace, there is no Module or Handler class.

I was able to uninstall the RC of Glimpse, and install the .87 version, and that worked as advertised. Unfortunately, I want the Timing functions, which seem to only be in the RC. I uninstalled the 0.87 version and tried the RC again and am getting the same issues.

**Comment by jondavis-ineight** [comment]
I am experiencing this problem as well. I did run install-package Glimpse.MVC5, and also Glimpse.AspNet and Glimpse.EF6. The web.config is updated with <system.webServer> with add module and add handler for glimpse. The assembly references include Glimpse.Ado, Glimpse.AspNet, Glimpse.Core, Glimpse.EF6, and Glimpse.Mvc5.
