### ISSUE TITLE
Create alternate ILMerge-free build

### ISSUE THREAD

**Issue by nikmd23** [Glimpse/Glimpse#239]
Create an alternate `pack` command in our psake script that eschews ILMerge in favor of NuGet dependencies. The alternate NuGet package could be build and used locally for when users have issues like the one in #159.

The alternate NuGet package would have a dependency chain like so:

```
+--------------+
| Glimpse.Mvc3 |
+--------------+
|
|   +--------------+
+--+| Glimpse.Core |
    +--------------+
    |
    |   +---------+
    +--+| antixss |
    |   +---------+
    |
    |   +-------------+
    +--+| Castle.Core |
    |   +-------------+
    |
    |   +-----------------+
    +--+| Newtonsoft.Json |
    |   +-----------------+
    |
    |   +------+
    +--+| NLog |
    |   +------+
    |
    |   +--------------------+
    +--+| Tavis.UriTemplates |
        +--------------------+
```

**Comment by codegecko** [comment]
This has been closed but none of the Nuget packages have been updated to depend on other versions. I'm happy to fork and send in a PR cause my current project debugging causes issues when I try and use Newtonsoft.Json.
