### ISSUE TITLE
Make Glimpse work with Microsoft.AspNet.WebApi.HelpPage

### ISSUE THREAD

**Issue by jFensch** [Glimpse/Glimpse#282]
With both Glimpse and Microsoft.AspNet.WebApi.HelpPage installed, HelpPage output is empty.

**Comment by Terebi42** [comment]
@areijngoudt I have that working, sortof.  I fortunately had a helper class for all my Rest calls from the MVC app to the WebApi app. I created a flag that would let me switch from using the real rest calls to the server, to instead using the "in memory http server" to host the webapi within the mvc app. This keeps all routing logic in place, but skips some serialization and wire overhead - so it isn't a perfect simulation.

It essentially turns my n-tier app into a single tier web app. 

When I flip the switch, I get end to end profiling from MVC into the EF backend, which is super slick.

Can't use it in a real environment, but its still pretty killer.

real n-tier support would be awesome, but the issue would be how would the results be returned from webapi to the client. You could inject some code into the mvc app that would go fetch info from the app tier (using the glimpse session name?) and then pull it back, but thats gonna be hokey.

How do the big boys (new relic etc) track things across tiers?
