### ISSUE TITLE
Provide support for Nhibernate

### ISSUE THREAD

**Issue by jamesfoster** [Glimpse/Glimpse#299]
Hi

I'm trying to get Nhibernate to work with glimpse. I've got Glimpse.ADO and since it replaces the DbProviderFactories table i thought it would just work. I've even poked in my own IDriver but it seems to only print out SELECTs and not INSERTs or UPDATEs.

How should I configure Nhibernate to work with glimpse?

I notice there's some code in Glimpse specifically for nhibernate. #141 and #156. But there are no packages for it?

Any help is greatly appreciated.

Thanks

**Comment by brdmllr** [comment]
I was able to get SELECT, INSERT, UPDATE and DELETE statements to appear in the Glimpse SQL tab by creating a derived class from NHibernate.Driver.SqlClientDriver, getting an instance of SqlClientFactory from DbProviderFactories and overriding the CreateConnection and CreateCommand methods to use the equivalent methods on the SqlClientFactory instance.

I then specify the name of the derived class manually in my NHibernate SessionFactory configuration. I'm not sure how to go about wiring this up automatically.

https://gist.github.com/brdmllr/26a3bd56ee3cf0b4a1cd/de676f17065a5382dc5c3ce3ed09f10eb3e8c9b8

**Comment by stevenlauwers22** [comment]
@brdmllr, @nikmd23, @avanderhoorn I released my Glimpse NHibernate plugin a few months ago.
It should work with all NHibernate versions and all kinds of databases that NHibernate supports, checkout the github repo for more info: https://github.com/stevenlauwers22/Glimpse.NHibernate

**Comment by avanderhoorn** [comment]
Ya! Thanks @stevenlauwers22.
