### ISSUE TITLE
Customer ActionInvoker being overridden

### ISSUE THREAD

**Issue by chaoaretasty** [Glimpse/Glimpse#328]
I have a custom ActionInvoker which overrides FindAction (it's part of a CMS that allows for content pages ontop of any of the controllers). When Glimpse is enabled the overridden FindAction is never called.

**Comment by bmmathe** [comment]
It looks like a check-in mentioned this issue a few days ago.  Can I get an update on whether this was fixed or if I can contribute in some way.  

Thanks!
