### ISSUE TITLE
0 bytes returned when controller content type is text/css and gzipped

### ISSUE THREAD

**Issue by struct78** [Glimpse/Glimpse#33]
I have 2 controllers that do similar things: Minify and compress CSS and Javascript files on the fly, store them in the cache, then return the output to the browser. When glimpse is turned on, and minification is turned on, the CSS controller returns 0 bytes.

In Chrome I get the following error: Error 330 (net::ERR_CONTENT_DECODING_FAILED): Unknown error.

There is very little difference between the javascript, and the CSS controller, the only real difference is content type. Both of them are gzipped.

When I remove the gzip attribute, it works as normal.

Here are the headers that are returned to the browser when the CSS controller is called (gzip + minify enabled):

HTTP/1.1 200 OK
Cache-Control: public
Transfer-Encoding: chunked
Content-Type: text/css; charset=utf-8
Content-Encoding: gzip
Expires: Sun, 01 May 2011 00:05:42 GMT
Last-Modified: Thu, 21 Apr 2011 00:05:42 GMT
Server: Microsoft-IIS/7.5
X-AspNetMvc-Version: 3.0
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Thu, 21 Apr 2011 00:05:42 GMT

Here are the headers that are returned to the browser when the Javascript controller is called (gzip + minify enabled):

HTTP/1.1 200 OK
Cache-Control: public, max-age=86400
Content-Type: text/html; charset=utf-8
Content-Encoding: gzip
Expires: Fri, 22 Apr 2011 00:06:46 GMT
Last-Modified: Thu, 21 Apr 2011 00:06:46 GMT
Vary: *
Server: Microsoft-IIS/7.5
X-AspNetMvc-Version: 3.0
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Thu, 21 Apr 2011 00:06:56 GMT
Content-Length: 170550

**Comment by glennweb** [comment]
Yip, I was having a problem with an html template being loaded with ajax. Added the following to the glimpse config. 

```
 <runtimePolicies>
      <uris>
        <add regex=".*/*.html"/>
      </uris>
  </runtimePolicies>
```
