### ISSUE TITLE
Glimpse v2 - Suppport chained service calls

### ISSUE THREAD

**Issue by swensorm** [Glimpse/Glimpse#337]
This is a feature request to support chaining information from service calls and displaying them in a glimpse tab.  This is extremely useful in SOA environments where applications call services which may call other services.

I hacked together something to work with 0.87 but haven't had any time to port it to 1.0.  Basically how it worked was that a wrapper over my http client included the glimpse cookie information in the request which was then read by the service that had glimpse installed, captured all the information, and returned the response header with the glimpse capture ID.  The client would receive a tab that contained all the service calls and a link to drill into them.  I stole some internals from the Ajax tab and used similar functionality to change the client context to that of the service call (making a request to the service using the capture ID) and displaying all of its capture information.

Another option could be to include the service calls timeline in that of the parent so you can visualize every detail of what occurred (db queries, controller action methods, filters, etc.) through the entire life of the request.  I personally liked the drill down so you could get the rest of the tabs filled with the service's information (configuration, etc.) and the service didn't have to return the capture data until it was needed.

It was definitely not without its challenges.  One of the worst was not being able to identify a way to automatically hookup proxying http requests in the framework.  I had to make a generic wrapper that everything used and then a glimpse package that then wrapped the generic.  I really love how glimpse "just works" without needing to modify code so I wasn't particularly happy about that way but it worked.

Sorry for the TL;DR.  Please let me know if you think this might be a useful feature and hopefully someday I'll have time to work on it again.  Thanks!

**Comment by sehgalg** [comment]
Is this in progress? Just wanted to know how much work on this has been completed.

**Comment by avanderhoorn** [comment]
Good amount has been done already - https://github.com/avanderhoorn/Glimpse.Prototype/. Feel free to take a look. No eta on release date yet though.

**Comment by Terebi42** [comment]
Any updates about this 2 years later?
