### ISSUE TITLE
Error when installing Glimpse nuget package for ASP.NET (Unable to cast object of type 'Castle.Proxies.RouteBaseProxy')

### ISSUE THREAD

**Issue by jsonmez** [Glimpse/Glimpse#344]
When using Glimpse.AspNet 1.2.2 from nuget

Unable to cast object of type 'Castle.Proxies.RouteBaseProxy' to type 'Microsoft.AspNet.FriendlyUrls.FriendlyUrlRoute'.

Occurs after installing Glimpse.

Steps to reproduce.
1. Create Web Forms Applications
2. Install Glimpse.AspNet 1.2.2 using nuget package manager
3. Run application, error occurs.

**Comment by fomenta** [comment]
On 12-aug-2015 I just installed glimpse into a brand new default asp.net web application project using nuget and ran it with the same result. Using Visual Studio 2012. The error came back again. What can I do?
