### ISSUE TITLE
high memory usage on request /Glimpse.axd?n=glimpse_request&requestId=d8e5d404-5ee3-488a-a748-c6d2461429b1&hash=f98a77a7&callback=glimpse.data.initData

### ISSUE THREAD

**Issue by salamonlukasz** [Glimpse/Glimpse#394]
While executing this request memory usage of w3wp goes up to 4.8 GB and then 500 error is returned. 
I'm using glimps.mvc4. page on which that happens it's quite heavy in terms of backend operations. We using a lot of "render action" and making a lot of WCF Data Service requests. I've managed - couple times - to opened glimps panel go to mvc action listing tab (don't remember exact name of the tab) but then when i wanted to change to metadata panel just hanged and browser needed to be restarted. 

Update:

On a different page in our app it takes age to load and finally loads. The size of response from this request is 207.9MB!!

If any other information is required - comment. 

Error page : 

Server Error in '/' Application.
Overflow or underflow in the arithmetic operation.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.ArithmeticException: Overflow or underflow in the arithmetic operation.

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:

[ArithmeticException: Overflow or underflow in the arithmetic operation.]

[HttpException (0x80004005): An error occurred while communicating with the remote host. The error code is 0x80070216.]
   System.Web.Hosting.IIS7WorkerRequest.RaiseCommunicationError(Int32 result, Boolean throwOnDisconnect) +4373201
   System.Web.Hosting.IIS7WorkerRequest.FlushCore(Boolean keepConnected, Int32 numBodyFragments, IntPtr[] bodyFragments, Int32[] bodyFragmentLengths, Int32[] bodyFragmentTypes) +12510493
   System.Web.Hosting.IIS7WorkerRequest.FlushCachedResponse(Boolean isFinal) +831
   System.Web.HttpResponse.UpdateNativeResponse(Boolean sendHeaders) +1110
   System.Web.HttpRuntime.FinishRequestNotification(IIS7WorkerRequest wr, HttpContext context, RequestNotificationStatus& status) +336

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.18044

**Comment by kamranayub** [comment]
I am running into the same issue right now, latest version of all packages (1.8.x).

My response JSON, when saved, is 293MB and w3wp process climbs to 4GB and crashes. Chrome will crash the tab on my site with Glimpse enabled :boom:
