### ISSUE TITLE
Add more context information when subscribing/publishing with the pubsub client component

### ISSUE THREAD

**Issue by CGijbels** [Glimpse/Glimpse#416]
I'm getting my way into the whole pub/sub architecture, but, call me picky, it would be nice to have a (runtime) view of what methods are subscribed to which events and where those events are being published. 

That would make it easier to understand the flow of events in the whole app, and if you make it available at runtime, it can be a debug assistant as well.

Maybe this can be done by adding more context when calling `pubsub.subscribe` and `pubsub.publish`

so a call like this

```JavaScript
pubsub.subscribe('action.shell.opening', listenStart);
```

could be changed into something like this

```JavaScript
pubsub.subscribe(
  'action.shell.opening',
  listenStart,
  { 
    description: 'Activate listening to Ajax requests in the Ajax tab',
    module: 'glimpse.ajax'
  });
```

and a call like this

```JavaScript
pubsub.publish(
  'trigger.data.context.switch', 
  { 
    requestId: $(this).attr('data-requestId'), 
    type: 'ajax' 
  });
```

could be changed into something like this

```JavaScript
pubsub.publish(
  'trigger.data.context.switch', 
  { 
    requestId: $(this).attr('data-requestId'), 
    type: 'ajax' 
  },
  {
    description: 'Ajax request selected in HUD',
    module: 'glimpse.hud'
  });
```

and once the code explains why it is subscribing or publishing, it is easier to see at runtime if it all makes sense, and at design time you can use that information to do some impact analysis.

What do you think?

**Comment by avanderhoorn** [comment]
Closing for now.
