### ISSUE TITLE
Improve documentation for Glimpse

### ISSUE THREAD

**Issue by avanderhoorn** [Glimpse/Glimpse#434]
Documentation is one of those things that separates OSS projects from each other. We want to improve this experience and make as good as possible. 

Currently we use the [Wiki of this repository](https://github.com/Glimpse/Glimpse/wiki) to capture the docs and publish these to the [GetGlimpse site](http://getglimpse.com/Help/).

**Comment by run1206** [comment]
Checked earlier and couldn't find this bug documented. The below issue is not code related.
I'm seeing a bunch of broken links in the "Create an Extension" section of the contributing.md file.

File: https://github.com/Glimpse/Glimpse/blob/master/contributing.md
Broken Link: [Creating your own custom extensions and tabs](https://github.com/Glimpse/Glimpse/blob/master/Custom-Tabs)
Broken Link: [Creating your own custom runtime policies](https://github.com/Glimpse/Glimpse/blob/master/Custom-Runtime-Policy)

![glimpse-broken-links](https://cloud.githubusercontent.com/assets/16143658/11603974/d7506014-9ab4-11e5-991f-d8d1044aa99c.JPG)

I'd like to update the links in the contributing.md file if that's ok.
