### ISSUE TITLE
Various inspect links in the glimpse user interface say they have loaded, but nothing happens

### ISSUE THREAD

**Issue by anupshah** [Glimpse/Glimpse#479]
Hi,

This is what I have:
- Latest Glimpse from NuGet: Glimpse Core 1.5.0 and Glimpse Asp.NET 1.3.1. 
- IIS 7.5 with .NET 4.5.
- ASP.NET Web Forms (but mostly AJAX via ASHX requests)

It runs fine without needing to change any defaults that the NuGet install applies.

I can see basic timelines/requests etc in the Glimpse view when enabled. But I cannot drill down anywhere. For example, in the AJAX tab, if I click an "inspect" link, it load something and goes green, but I don't see any further data anywhere.

Also the trace doesn't list any server side operations (and I know there are quite a few!). Normal trace.axd shows it.

E.g. the various "Inspect" links, in the "Ajax" and "History" tabs are all defined with an href of '#'. But I can see you use data attributes to eventually become querystrings in the URL. But the # remains at the end, e.g.

http://localhost/myApp/Glimpse.axd?n=glimpse_popup&requestId=7ae2b35a-c839-45aa-b8d7-819b5ced2960&hash=c6df3424#

In my app, I follow a common pattern to manage AJAX history (back button support etc), by working with the contents after the #. If there is no content after the hash, my app performs a default action.

When your "inspect" links (and other such links with href="#")  are clicked, these cause extra interactions as a result. Is it possible that when you generate your links that you don't use # in it? Could it be this that is preventing those links from working as well?

Admittedly in Firefox if I use firebug to edit those links and remove the # manually I still can't get the "Inspect" links to work.

Any pointers as to where to look or what further info I can provide? Apologies if this is already answered elsewhere; I missed it when searching around...

Thanks!

**Comment by hbopuri** [comment]
Does glimpse work for Ajax calls using EXTJS frameworks. my ajax calls are on a click event, its a single page application, I don't see any log in Ajax tab on glimpse. Am I missing any configuration or glimpse has not yet come to that point to support such requests?

**Comment by avanderhoorn** [comment]
@hbopuri I am assuming this is related to the question you raised over on the other issue. I'm going to keep the conversation over there.
