### ISSUE TITLE
Umbraco 6.13 and MVC

### ISSUE THREAD

**Issue by bradleykronson** [Glimpse/Glimpse#518]
Has anyone managed to get Glimpse working in Umbraco with MVC enabled. 

Whenever I enable Glimpse all web site pages return a 404

**Comment by JimBobSquarePants** [comment]
Why is this issue closed?

**Comment by rekosko** [comment]
Exactly... I'm trying to install Glimpse MVC to my Umbraco 7 project and it's not working for frontend sites... It would be great to find out how to fix this. I know that there's a package but as far as I remember it may be outdated.
