### ISSUE TITLE
Make Glimpse faster on startup

### ISSUE THREAD

**Issue by TimLovellSmith** [Glimpse/Glimpse#523]
[I apologize if I'm reporting an issue has already been addressed. I'm still using Glimpse 1.2.0.]

I noticed that Glimpse reflects across all the dlls in the execution folder at app startup. And this is about 9% of our app startup time. See this bug for context.

https://github.com/NuGet/NuGetGallery/issues/1400

Is there a way to turn this behavior off?
Regardless, I think it would be great if Glimpse could be a little bit more selective about how it loads dlls for reflection.

**Comment by jtheisen** [comment]
People who do gratuitous assembly scanning indeed deserve a public whipping.

Also perhaps this information should be somewhere more prominent. It was difficult to find even though knew what I was looking for.

**Comment by jtheisen** [comment]
> they all have parameterless constructors

No, the don't - or at least not any more.

I [tried to write my own](https://gist.github.com/jtheisen/fab9681f778232915428a2a97e445040) `IServiceLocator`, but it appears I need to write a bit of an IoC container as well...

**Comment by pltaylor** [comment]
@jtheisen This issue was closed 2 1/2 years ago and even though I haven't kept up with the project the I am pretty sure the landscape has changed considerably since these comments were made.

**Comment by jtheisen** [comment]
@pltaylor It was closed on the basis to be fixed in an upcoming version 2, which isn't yet there.

This should really be reopened, but maybe I'm just filing a new issue.

Currently, Glimpse is basically broken for larger projects. I have a warmup overhead of 10s due to Glimpse, even when turned off.

**Comment by pltaylor** [comment]
@jtheisen I'm not making any comment of the appropriateness of your comment, merely that the suggestions and comments about the actual code may not be valid any more.
