### ISSUE TITLE
Glimpse.ADO + Telerik.Reporting Issues

### ISSUE THREAD

**Issue by kpatmor** [Glimpse/Glimpse#538]
Currently I have Glimpse + Glimpse.ADO  installed in an ASP.NET 3.5 application. It works great for all of the pages except for those that have Telerik Reports. 

Whenever I run one of the reports, it displays an error like: "An error has occurred while processing Report 'ReportNameHere': Procedure or function 'storedProcedureName' expects parameter '@ParameterName', which was not supplied." There is no stack trace or other mechanism for debugging this that I can tell because it's internal to the Telerik components.

The Telerik reports use a Telerik.Reporting.SqlDataSource to retrieve the data for the report. I believe that there is some conflict with the Glimpse DbAdapter/DbCommand objects, which is why the parameters aren't set properly.

Since the Glimpse.ADO code replaces the DbProviderFactory entries with its wrapped versions during initialization of the component, excluding these pages with a custom policy or a blacklist url does not help as a workaround. I either have to turn off Glimpse for the whole app, or remove the Glimpse.ADO dll completely.

Any thoughts on how I could workaround this so that I get the benefits of the Sql tab on other pages, even if I can't use it on these report pages?

**Comment by isaacOjeda** [comment]
Hi everybody,

I would like to know if this issue has now a solution? Like others, I'm using Telerik.Reporting and started using Glimpse because it's just great but i'm with this problem too. At the moment I uninstalled the EF6 and ADO modules but it would be great if i there's a solution for this.

Thank you!
