### ISSUE TITLE
Glimpse.WebForms changes meaning of trace element at web.config - it renders trace in pages

### ISSUE THREAD

**Issue by jirikanda** [Glimpse/Glimpse#618]
This is in web.config
<trace enabled="true" pageOutput="false" />

This means, trace is enabled and accessible by ~/trace.axd. Trace is not rendered at the end of pages.

After installing Glimpse.WebForms, every page contains trace - it behaves like pageOutput="true".

![image](https://f.cloud.github.com/assets/5111719/1499429/53a84600-4859-11e3-8445-d4780816a011.png)

**Comment by Alkapin** [comment]
Hi,

I have just installed Glimspe.WebForms v 1.1.1 and this error seems to be still there.

Any one of these lines in the web.config

    
    <trace writeToDiagnosticsTrace="true" enabled="true" pageOutput="false"/>
    <trace writeToDiagnosticsTrace="false" enabled="false" pageOutput="false"/>

still result in the tracing info rendered directly on the page. Interesting is that trace container appears in the seemingly random location in the DOM tree.

![image](https://cloud.githubusercontent.com/assets/7593924/8121757/2ae8884e-1065-11e5-86d7-9989aff75268.png)
