### ISSUE TITLE
Problem with multiple web projects

### ISSUE THREAD

**Issue by andrewQwer** [Glimpse/Glimpse#640]
Hi,

I have two ASP.NET MVC 5 projects in a single solution. The first one is used as main web application, the second one is used to return JSON data (I have MVC 5 controllers that return JsonResult and Web API controllers in this project). 
So the problem is that I use Glimpse for the first application only, but when I run the second application it fails with error `Could not load file or assembly 'Glimpse.AspNet...'` But I don't use Glimpse with the second application, i don't have any references so why does my application fail with such error? Glimpse was installed with NuGet.

Thank you.

**Comment by antonvasilenko** [comment]
thanks, it really helped a lot

**Comment by avanderhoorn** [comment]
@antonvasilenko Great to hear :D
