### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by nikmd23** [Glimpse/Glimpse#651]
It'd be awesome if Glimpse supported keyboard shortcuts. A few I'd like to see added:

- [x] Maximize (from HUD to "full Glimpse", same as clicking G)
- [x] Minimize (from "full Glimpse" to HUD, same as clicking down arrow)
- [ ] Pop-up HUD Section (same as hovering over a HUD section.)

    This could perhaps use [Modifier]+[1], [Modifier]+[2], [Modifier]+[N] just like browsers do to switch tabs.
- [ ] Tab switching (also leveraging the familiar browser tab switch keys as described above)
- [x] Launch Help (same as clicking the '?')
- [ ] Any others?

**Comment by samranjbari** [comment]
@nikmd23 Is this feature still being considered? I'd love to help!

**Comment by avanderhoorn** [comment]
Still being considered but we have been putting the majority of our focus in v2. Unfortunately v2 is still a little way out. That said, if you are interested in doing this for v1 we would love it to make it in. Any ideas on how you would like to go about it?

**Comment by samranjbari** [comment]
Initial thoughts:
Would have a checkbox on the HUD to disable the shortcut keys. (or could be part of glimpse configuration settings)
Would define a set of overridable keys with their mapping actions.
Simple.

**Comment by avanderhoorn** [comment]
Sounds good to me. I think we could start out with the `.\glimpse.axd` and then bring it into HUD. It should be pretty easy to get the shortcuts hooked in as most of the system is run off messages and you can simulate clicks by publishing messages that are sent when clicks occur. What are you looking to use for capturing the clicks?
