### ISSUE TITLE
Fail using Glipse EF6.1 alpha 1 and MySQL EF6

### ISSUE THREAD

**Issue by ftoyon** [Glimpse/Glimpse#714]
Hi !

I'm try to use Glimpse EF6 with MySQL EF6 and it' throw exception : 
Unable to cast object type 'MySql.Data.MySqlClient.MySqlConnection' to type 'Glimpse.Ado.AlternateType.GlimpseDbConnection'.

connectionString="server=localhost;user id=xxx;persistsecurityinfo=True;database=xxx;password=xxx;"
providerName="MySql.Data.MySqlClient"

Installed packages : 
  package id="EntityFramework" version="6.1.0-alpha1" targetFramework="net45"
  package id="Glimpse" version="1.8.1" targetFramework="net45"
  package id="Glimpse.Ado" version="1.7.0" targetFramework="net45"
  package id="Glimpse.AspNet" version="1.7.0" targetFramework="net45"
  package id="Glimpse.EF6" version="1.6.0" targetFramework="net45"
  package id="Glimpse.Elmah" version="1.1.1" targetFramework="net45"
  package id="Glimpse.Mvc5" version="1.5.2" targetFramework="net45"
  package id="MySql.Data" version="6.8.3" targetFramework="net45"
  package id="MySql.Data.Entities.EF6" version="6.8.3" targetFramework="net45"

Stack trace : 

[InvalidCastException: Impossible d'effectuer un cast d'un objet de type 'MySql.Data.MySqlClient.MySqlConnection' en type 'Glimpse.Ado.AlternateType.GlimpseDbConnection'.]
   Glimpse.EF.AlternateType.GlimpseDbProviderServices.GetDbProviderManifestToken(DbConnection connection) +37
   System.Data.Entity.Core.Common.DbProviderServices.GetProviderManifestToken(DbConnection connection) +118

[ProviderIncompatibleException: The provider did not return a ProviderManifestToken string.]
   System.Data.Entity.Core.Common.DbProviderServices.GetProviderManifestToken(DbConnection connection) +459
   System.Data.Entity.DbModelBuilder.Build(DbConnection providerConnection) +118
   System.Data.Entity.Internal.LazyInternalContext.CreateModel(LazyInternalContext internalContext) +94
   System.Data.Entity.Internal.RetryLazy`2.GetValue(TInput input) +248
   System.Data.Entity.Internal.LazyInternalContext.InitializeContext() +618
   System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType) +26
   System.Data.Entity.Internal.Linq.InternalSet`1.Initialize() +72
   System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext() +21
   System.Data.Entity.Infrastructure.DbQuery`1.System.Linq.IQueryable.get_Provider() +64
   System.Data.Entity.QueryableExtensions.FirstOrDefaultAsync(IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken) +218
   System.Data.Entity.QueryableExtensions.FirstOrDefaultAsync(IQueryable`1 source, Expression`1 predicate) +113
   Microsoft.AspNet.Identity.<FindByNameAsync>d__13.MoveNext() +273
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   Microsoft.AspNet.Identity.<RoleExistsAsync>d__d.MoveNext() +603
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +49
   Microsoft.AspNet.Identity.AsyncHelper.RunSync(Func`1 func) +120
   PlateformeTechnique.MvcApplication.Application_Start() in c:\Projets\CG45-APA\dotNet\Applications\PlateformeTechnique\Global.asax.cs:38

[HttpException (0x80004005): The provider did not return a ProviderManifestToken string.]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +12949749
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +175
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +304
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +404
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +475

[HttpException (0x80004005): The provider did not return a ProviderManifestToken string.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +12966756
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +159
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +12806561

**Comment by protonyx** [comment]
The root cause of this exception seems to be coming from the MySqlProviderServices class. After thumbing through the MySQL connector source code, I discovered that the GetDbProviderManifestToken function is casting the DbConnection as a MySqlConnection to extract the connection string:

`MySqlConnectionStringBuilder msb = new MySqlConnectionStringBuilder((connection as MySqlConnection).Settings.ConnectionString);`

instead of using the ConnectionString property of the DbConnection base class, like so:

`MySqlConnectionStringBuilder msb = new MySqlConnectionStringBuilder(connection.ConnectionString);`

According to [MySQL bug 61230](https://bugs.mysql.com/bug.php?id=61230), this problem was discovered and fixed years ago, but yet the latest source code still shows the offending code.
