### ISSUE TITLE
Improve ViewState processing for Parameter Collections

### ISSUE THREAD

**Issue by avanderhoorn** [Glimpse/Glimpse#725]
Currently, we aren't doing any special processing for DataSource Parameter Collections. This item would see that we add the required logic to visualise this correctly.

**Comment by cezarant** [comment]
Hi guys, i'm newbie in Glimpse. I realized that , all the issues, this is the most appropriate so that I can start. Someone is working on this thread? @nycdotnet You had any progress?

**Comment by nycdotnet** [comment]
Hi,
I think this fell off my radar.  I don't recall if I made any progress on it, so feel free to start fresh.  Good luck!
