### ISSUE TITLE
Glimpse.WindowsAzure - what's next?

### ISSUE THREAD

**Issue by maartenba** [Glimpse/Glimpse#729]
As you [may have seen](http://blog.maartenballiauw.be/post/2013/12/30/Introducing-Glimpse-plugins-for-Windows-Azure.aspx), the first two Glimpse packages for Windows Azure are on their way:
* Glimpse.WindowsAzure package displaying runtime information
* Glimpse.WindowsAzure.Storage collecting information about traffic from and to storage

Once we release those officially, what would be the next Windows Azure component you want to have a glimpse into? Service bus? Caching? Others?

**Comment by justSteve** [comment]
The original blog post (http://blog.getglimpse.com/2013/12/30/a-glimpse-into-windows-azure/) points to  https://www.myget.org/F/glimpse-windowsazure/ which is turning up dead for me.

**Comment by ryandle** [comment]
@maartenba  @avanderhoorn that [package](https://www.nuget.org/packages/Glimpse.WindowsAzure.Storage) only had one beta version published in Jan 2014. Is there more work that needs to be done before a 1.0 release?

**Comment by avanderhoorn** [comment]
@maartenba is more up with progress on this one.

**Comment by maartenba** [comment]
Not a lot of progress, as no feedback from users at the time. Feel free to fork/adapt/extend.
