### ISSUE TITLE
elmah for glimpse plugin does not seem to work after upgrading to 0.82

### ISSUE THREAD

**Issue by iamandycohen** [Glimpse/Glimpse#73]
I am using Glimpse for MVC3.

Everything works as expected except the Elmah tab is no longer visible.

I include the script as necessary:
~/Glimpse/Resource/?resource=Pager receives a 404 not found

I have verified Elmah works itself by accessing via elmah.axd

I have the following assemblies in my references:

Elmah
Glimpse.Core
Glimpse.Elmah
Glimpse.Mvc3
Newtonsoft.Json
Tall.Glimpse.DependencyPlugin

Glimpse Config Settings:

This section details the Glimpse settings in your web.config file.

```
On = True
Allowed IP's =
    127.0.0.1
    ::1
Allowed ContentType's =
    text/html
Blacklisted Plugins =
```

Your Settings:

This section tells you how Glimpse sees your requests.

```
IP = ::1
glimpseState = On
```

Plugins:

This is the list of Glimpse plugins for this web application. Glimpse plugins show up as individual tabs in the Glimpse client. Plugins with a strike line through them are not loaded. You can stop a plugin from being loaded by adding it to the glimpse/pluginBlacklist section of your web.config.

```
Glimpse.Core.Plugin.Request
Glimpse.Core.Plugin.Environment
Glimpse.Core.Plugin.Trace
Glimpse.Core.Plugin.Config
Glimpse.Core.Plugin.Server
Glimpse.Core.Plugin.Session
Glimpse.Mvc3.Plugin.Binders
Glimpse.Mvc3.Plugin.Execution
Glimpse.Mvc3.Plugin.MetaData
Glimpse.Mvc3.Plugin.Routes
Glimpse.Mvc3.Plugin.Views
```

**Comment by vm1991** [comment]
Stiil getting the above error.
I am using elmah plugin for glimpse and i included the tag 
<script src="<%: Url.Content("~/Glimpse/Resource/?resource=Pager") %>" type="text/javascript"></script>

But on runtime am getting this ~/Glimpse/Resource/?resource=Pager receives a 404 not found.

There is no Glimpse directory anywhere in the web project.

**Comment by CGijbels** [comment]
@vm1991 maybe it is better to contact the owner of the [Glimpse for Elmah plugin](https://github.com/stevenlauwers22/Glimpse.Elmah/) , he'll be in a better position to help you with the integration

**Comment by stevenlauwers22** [comment]
@vm1991, you're using an outdated version of the plugin. Please upgrade to a later version to get rid of this error.

**Comment by vm1991** [comment]
@stevenlauwers22 Actually in my case Elmah tab is visible, but it displays only the top 15 records from Elmah log and pager is also not available.
I have installed Glimpse for Elmah plugin  v 1.1.1 through Nuget packages. I can't see any updates for this package.Is there any new version?

**Comment by stevenlauwers22** [comment]
@vm1991 I removed the paging feature a while back, since normally with Glimpse you're only interested in what happened during the lifetime of the last page request. If you want to see more than 15 errors, you'll have to open the elmah.axd page.

So, you shouldn't be getting this error if you're using v1.1.1 Are you sure you're using the latest version of the plugin?
