### ISSUE TITLE
Casting problems between Castle.Proxies and DevExpress Model Binder

### ISSUE THREAD

**Issue by amalbala** [Glimpse/Glimpse#760]
I have just installed Glimpse MVC5 on a project that is using DevExpress for UI controls. We use the default binder and cast it to perform validation and file actions. So in the controller constructor we have;

var binder = (DevExpressEditorsBinder) ModelBinders.Binders.DefaultBinder;
binder.UploadControlBinderSettings.ValidationSettings = ValidationSettings;
binder.UploadControlBinderSettings.FileUploadCompleteHandler = PrecitaController.ImageUpload_FileUploadComplete;

But the first sentence throws a cast exception:

Unable to cast object of type 'Castle.Proxies.DefaultModelBinderProxy' to type 'DevExpress.Web.Mvc.DevExpressEditorsBinder'.

In global.asax we define:
ModelBinders.Binders.DefaultBinder = new DevExpress.Web.Mvc.DevExpressEditorsBinder();

Any idea how to solve it?

Thanks in advance

**Comment by dchaib** [comment]
I have the same issue with a custom route in RouteTable. Is there a new solution? Blacklisting kind of defeats the purpose of adding Glimpse in the first place...
