### ISSUE TITLE
Unable to view SQL on SQL Tab when using transactions

### ISSUE THREAD

**Issue by shady14u** [Glimpse/Glimpse#772]
When wrapping the DB context with a transaction per request the SQL tab will not show SQL and throws:
```
System.NullReferenceException: Object reference not set to an instance of an object. at Glimpse.Ado.Model.ConnectionMetadata.RegiserTransactionStart(TransactionMetadata transaction) at
Glimpse.Ado.Model.MessageAggregator.AggregateTransactionBegan() at 
Glimpse.Ado.Model.MessageAggregator.Aggregate() at Glimpse.Ado.Tab.SQL.GetData(ITabContext context) at 
Glimpse.Core.Framework.GlimpseRuntime.ExecuteTabs(RuntimeEvent runtimeEvent)
```

If I comment out the transaction.BeginTransaction() and the Commit. then the SQL Tab displays fine.

I am using MVC5 and EF 6.0.2 and wrap my requests like the following

on Application_BeginRequest I create a transaction and put it in the HttpContext Items collection

on Application_EndRequest I look for any errors and commit or roll back the transaction

**Comment by avanderhoorn** [comment]
@robdmoore would be great if you can give it a crack, would love to get the fix into the next release.

**Comment by robdmoore** [comment]
Nice - looks like someone else did this :)

When is the next release coming out?

Thanks mate

**Comment by NotMyself** [comment]
Looks like I just ran into this bug with version 1.7.3. Has 1.7.4 shipped yet? or soon?

**Comment by avanderhoorn** [comment]
I'm going to try and get a release out early next week.

**Comment by avanderhoorn** [comment]
This is just waiting on one feature (keyboard shortcuts) to get in and then we will release.

**Comment by NotMyself** [comment]
any updates @avanderhoorn ?

**Comment by NotMyself** [comment]
Any updates @avanderhoorn ?

**Comment by avanderhoorn** [comment]
@NotMyself Thanks for pining me. Let me sync with the rest of the team and I'll get back to you next week.

**Comment by NotMyself** [comment]
@avanderhoorn :+1:

**Comment by kedde** [comment]
Have 1.7.4 been released on nuget? Or will this issue only be addressed in asp.net core version? I'll see the vNext Milestone tag.

**Comment by jusefb** [comment]
Hi,

Will this be fixed any time soon?

**Comment by feitzi** [comment]
Why is this issue closed? There is now version released that fix this bug. Please release 1.7.4

**Comment by JesseKlaasse** [comment]
As far as I can see, Glimpse.Ado is still @ 1.7.3, and still contains the bug in this issue. Is there any news on this?

**Comment by NotMyself** [comment]
@JesseKlaasse for whatever reason the fix was never released to nuget and this issue was closed was closed without comment after months of ignoring the issue. Not much has happened here since @avanderhoorn was hired by microsoft.

**Comment by rspopovi** [comment]
Running into this issue still today. It's been five years since this issue was "fixed", but is still pending release???
