### ISSUE TITLE
Glimpse v2 - Improved Persistent Store Interface - WIP

### ISSUE THREAD

**Issue by nikmd23** [Glimpse/Glimpse#790]
The current [`IPersistenceStore`](https://github.com/Glimpse/Glimpse/blob/master/source/Glimpse.Core/Framework/IPersistenceStore.cs) (and corresponding [`IReadOnlyPersistenceStore`](https://github.com/Glimpse/Glimpse/blob/master/source/Glimpse.Core/Framework/IReadOnlyPersistenceStore.cs)) interface has a few problems that we would like to rectify in time for v2.

- It is difficult/impossible to re-hydrate serialized data that a persistence store may have serialized.
- Glimpse's serializer is not available to the persistence store.
- Some applications currently "sneak" data into the in-memory persistence store after the `Save()` operation. [This is described by @CGijbels](https://groups.google.com/d/msg/getglimpse-dev/oY7EfUD_q7k/dobdF4qaFfcJ) and should not be supported.
- Glimpse metadata doesn't *really* need to be stored in a persistent way.

In addition, there are several scenarios that could be enabled and improved by tweaks to the serialization store. This issue is a rough proposal describing ideas for the future of `IPersistenceStore`. Feedback is encouraged, but please stay on point by referencing the numbered bullets below.

---
  1. The biggest change I'd like to propose is removing the dependency on `GlimpseRequest`, and instead leverage JSON strings:

  ```c#
  // From:
  GlimpseRequest IReadOnlyPersistenceStore.GetByRequestId(Guid requestId) // &
  void IPersistenceStore.Save(GlimpseRequest request)

  //To:
  string IReadOnlyPersistenceStore.GetByRequestId(Guid requestId) // &
  void IPersistenceStore.Save(Guid requestId, string request, [TBD] int statusCode,  ...)
  ```

  `Save()` will now receive the serialized JSON string (*request*), along with several other parameters that would be used for indexing/querying the payloads (*requestId*, *statusCode*, *requestIsAjax* , etc).

  2. Pushing basically just strings to persistence store implementations lets them be very simple and focus on the task at hand: storing data in some backing store. In addition, they'd also need to be able to query the data store based on any of the "other parameters" that are passed in to `Save()`.
    - Glimpse does this type of querying already based on three properties: requestId, parentRequestId (for Ajax tab) and clientId (History tab).
    - You could envision a future where Glimpse would also let uses filter requests to only see those with errant http statuses, or requests that took over `X ms` to process.

  3. [JSON.NET 6.0 added support](http://james.newtonking.com/archive/2014/02/01/json-net-6-0-release-1-%E2%80%93-jsonpath-and-f-support) for [JSONPath](http://goessner.net/articles/JsonPath/), an XPath like query language. Leveraging JSONPath would allow Glimpse, independent of the `IPersistenceStore` implementation, to trim request payloads so that it could:
    - Enable lazy loading partial payloads to improve rendering performance of the Glimpse client. Most likely we'd want to use a hypermedia based JSON format like [HAL](http://stateless.co/hal_specification.html)* to help facilitate this.
    - Remove certain tabs from the payload to enable "security trimming" and/or user profiles.

  4. Technically we could also ensure data integrity by leveraging [JSON-schema](http://json-schema.org/), but I don't think this is required.
  5. We could also allow for payload updates (for example, storing the request timing information from HUD, which is generated client side and lost) via RFC 6902 - [JSONPatch](http://tools.ietf.org/html/rfc6902). @darrelmiller has [an implementation for .NET](https://github.com/tavis-software/Tavis.JsonPatch) we'd be able to leverage. This will allow us to tie in downstream indicators (browser or proxy integration) directly into the data that Glimpse is gathering.
  6. These recommended changes greatly increase our dependency on JSON.NET. As such, I'd also recommend removing the Serializer from `IConfiguration`. I just don't think a user will be able to replace it properly anymore.
  7. Many `IResource` implementations could be reduced/simplified.
  8. `IPersistanceStoreDecorator` could be created to add additional functionality to the persistence store. Mainly, an in memory caching mechanism to reduce response times.

---
*Note: HAL would also enable much richer request relationships. We currently have inflexible Ajax and Redirect based relations, these could be expanded with a proper format.*

**Comment by avanderhoorn** [comment]
Changed repo
