### ISSUE TITLE
bulkinsert and glimpse not wokring

### ISSUE THREAD

**Issue by debajyotimahanta** [Glimpse/Glimpse#795]
If i use bulkinsert i am getting error saying cannot find provider

**Comment by gedsol** [comment]
When trying to use EF6 and BulkInsert application throws the following exception:
BulkInsertProvider not found for 'Glimpse.Ado.AlternateType.GlimpseDbConnection.
To register new provider use EntityFramework.BulkInsert.ProviderFactory.Register() method'

After adding the following code:
EntityFramework.BulkInsert.ProviderFactory.Register<EntityFramework.BulkInsert.Providers.EfSqlBulkInsertProviderWithMappedDataReader>("Glimpse.Ado.AlternateType.GlimpseDbConnection")
I am getting another exception message:
{"Field _connectionString was not found in Type Glimpse.Ado.AlternateType.GlimpseDbConnection\r\nParameter name: propName"}

**Comment by jrt324** [comment]
https://efbulkinsert.codeplex.com/ 
using this ef extension cause this problem

**Comment by feitzi** [comment]
Yes, i also use the BulkInsertExtension and on calling BulkInsert(..) i get this Exception:

>BulkInsertProvider not found for 'Glimpse.Ado.AlternateType.GlimpseDbConnection. To register new provider use EntityFramework.BulkInsert.ProviderFactory.Register() method'

Please reopen this issue.

**Comment by hobbe5** [comment]
I'm getting the same error when having glimpse installed in my project. I'm using the repository pattern and the code is as such:
`public virtual void BulkInsert(IEnumerable<T> entities)
{
     Entities.BulkInsert(entities);
}`
