### ISSUE TITLE
Requests are stuck when using an async WebApi Controller that serves images

### ISSUE THREAD

**Issue by robertmuehsig** [Glimpse/Glimpse#797]
I described the problem on Stackoverflow, because I thought I do something wrong with WebAPI, but it seems the root cause is in the Glimpse Module:
http://stackoverflow.com/questions/23663202/async-webapi-controller-serving-images-pending-http-requests

In short: When using an async webapi controller that serves images the browser only requests the first 7 images and all other requests are pending.

Repo:
VS2013, .NET 4.5, WebApi
https://gist.github.com/robertmuehsig/d453b1ee6f413e10e974

WIth Glimpse Module:
![glimpse](https://cloud.githubusercontent.com/assets/756703/2981111/87473680-dbff-11e3-8015-fe98627e4afe.PNG)

When I remove the module from the system.webServer Modules list everything works as expected.

I use these packages:
```
     <package id="Glimpse" version="1.8.2" targetFramework="net45" />
     <package id="Glimpse.AspNet" version="1.8.0" targetFramework="net45" />
     <package id="Glimpse.Mvc5" version="1.5.3" targetFramework="net45" />
```

**Comment by darshitsolanki7** [comment]
Hello robertmuehsig,

I am also facing the issue like browser is not serving async request after 1 or 2 requests. it is going to pending state but it is working fine with localhost in IISExpress. 

I am not using any Glimpse package, below is code snippest. Any help would be appreciated

  internal async Task<List<PingInfo>> GetPingStatusInformation(int offset)
        {
            PopulateQueueData(offset);

            await RunTask();

            return listExecutingItemStatus;

        }

   private async Task RunTask()
        {
            listExecutingItemStatus = new List<PingInfo>();
            PingInfo pingInfo;

            prevTask = new Task(() =>
            {
                if (_QueuePingInfo.TryDequeue(out pingInfo))
                {
                    if (!_CancellationToken.IsCancellationRequested)
                    {
                        ExecuteTask(pingInfo);
                    }
                }

                for (int i = 0; i < _QueuePingInfo.Count; i++)
                {
                    nextTask = prevTask.ContinueWith((t1) =>
                    {
                        if (_QueuePingInfo.TryDequeue(out pingInfo))
                        {
                            if (!_CancellationToken.IsCancellationRequested)
                            {
                                ExecuteTask(pingInfo);
                            }
                        }
                    }, _CancellationToken);
                    prevTask = nextTask;
                }
            }, _CancellationToken);

            prevTask.Start();

            prevTask.Wait();
            nextTask.Wait();
        }

**Comment by robertmuehsig** [comment]
@darshitsolanki7 Mh - maybe your preTask/nextTask.Wait() method blocks something. But if this has nothing todo with Glimpse, maybe you should start a question on Stackoverflow.com?

**Comment by darshitsolanki7** [comment]
robertmuehsig - Thank you for your response. Yes, you are correct. prev/nexttask.wait() will wait synchronously and by using awit it is working fine. It was creating deadlock situation on earlier case and hence blocking the request.
