### ISSUE TITLE
EF5, MVC4, NET4.5, Oracle Db - Unable to determine the provider name for connection of type 'Oracle.DataAccess.Client.OracleConnection'

### ISSUE THREAD

**Issue by andriss** [Glimpse/Glimpse#809]
After getting this 'Unable to determine the provider name...' error, I tried all standard solutions I could find, but none helped. As last, I tried to uninstall Glimpse, and that helped. I  saw some other similar issues but all of them were closed and didn't use Oracle or EF5, so I guess I should create a new issue. Error is thrown when trying to query database.

**Stacktrace**:
```
[NotSupportedException: Unable to determine the provider name for connection of type 'Oracle.DataAccess.Client.OracleConnection'.]
   System.Data.Entity.ModelConfiguration.Utilities.DbConnectionExtensions.GetProviderInvariantName(DbConnection connection) +587
   System.Data.Entity.Internal.InternalConnection.get_ProviderName() +38
   System.Data.Entity.Internal.LazyInternalContext.InitializeContext() +346
   System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType) +18
   System.Data.Entity.Internal.Linq.InternalSet`1.Initialize() +52
   System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext() +15
   System.Data.Entity.Infrastructure.DbQuery`1.System.Linq.IQueryable.get_Provider() +37
   System.Linq.Queryable.SingleOrDefault(IQueryable`1 source, Expression`1 predicate) +63
```

**Development platform**:
* .NET 4.5
* Oracle Db
* ASP.NET MVC 4 & IIS
* EF5 Code First 

**Installed Glimpse packages**:
* Glimpse                        1.8.5 
* Glimpse.Ado                    1.7.1 
* Glimpse.AspNet                 1.8.0 
* Glimpse.EF5                    1.6.2
* Glimpse.Mvc4                   1.5.3

**Comment by avanderhoorn** [comment]
Unfortunately there isn't much I can do at the moment, its a known issue. That said, the progress is being tracked at #226
