### ISSUE TITLE
Entity Framework 6.1.1 - NullReferenceException

### ISSUE THREAD

**Issue by AndyWorral** [Glimpse/Glimpse#811]
Just updated to EF 6.1.1 and started having an issue with Glimpse on first DB access as app loads.  Had to remove EF6/Ado For glimpse to get site working again.

(part of error and stack trace)

Object reference not set to an instance of an object.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

Source Error: 

```
Line 19:         public Setting GetApplicationSettings()
Line 20:         {
Line 21:             return context.Settings.FirstOrDefault();
Line 22:         }
Line 23: 

Source File: c:\...\SettingsLogic.cs    Line: 21 
```

Stack Trace: 

```
[NullReferenceException: Object reference not set to an instance of an object.]
   Glimpse.Ado.AlternateType.GlimpseDbConnection.remove_StateChange(StateChangeEventHandler value) +15
   System.Data.Entity.Core.EntityClient.EntityConnection.Dispose(Boolean disposing) +66
   System.ComponentModel.Component.Dispose() +23
   System.Data.Entity.Internal.InternalContext.DisposeTempObjectContext() +289
   System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization() +655
   System.Data.Entity.Internal.RetryAction`1.PerformAction(TInput input) +208
   System.Data.Entity.Internal.LazyInternalContext.InitializeDatabaseAction(Action`1 action) +266
   System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType) +39
   System.Data.Entity.Internal.Linq.InternalSet`1.Initialize() +72
   System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext() +21
   System.Data.Entity.Infrastructure.DbQuery`1.System.Linq.IQueryable.get_Provider() +64
   System.Linq.Queryable.FirstOrDefault(IQueryable`1 source) +67
```

**Comment by dcadavona** [comment]
I've come across this error and I think it's storage related. My computer was running out of primary storage. About 150+ MB. When I free'd up additional 50MB (approx.), for a total of about 200 MB, all went okay.

**Comment by avanderhoorn** [comment]
@dcadavona this seems weird. Any chance that you can try and track down were the memory leak might be?

**Comment by francnuec** [comment]
Experiencing same issue now, and I'm using 6.1.3. Maybe @dcadavona is right. My hard drive is running low on storage. Trying to free up space now.

<code>
var userId = 1;
var user = context.Users.Where(u => u.id == userId).FirstOrDefault();
</code>

<code>
   at System.Data.Entity.Internal.Linq.InternalQuery`1.get_Expression()
   at System.Data.Entity.Internal.Linq.InternalSet`1.get_Expression()
   at System.Data.Entity.Infrastructure.DbQuery`1.System.Linq.IQueryable.get_Expression()
   at System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)
   at Project.Controllers.Api.UserController.PostFollowers(String userId, MessageDto message, String via) in d:\Documents\Visual_Studio_2012\Projects\Project\Project\Controllers\Api\UserController.cs:line 815
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
</code>

**Comment by avisser** [comment]
I had this issue as well with `System.Data.Entity.Internal.Linq.InternalQuery'1.get_Expression()` at the top of my stack trace like @francnuec. 

My fix was to force the connection open. I do have Glimpse installed in this project. Hope this might help.

```csharp
        var ctx = new MyContext(connStr);
        ctx.Database.Connection.Open(); // adding this line removed the error
        using (var tx = ctx.Database.BeginTransaction())
        {
          var leadEntity = //this line would throw
            ctx.ClientEntities.FirstOrDefault(
              ce => ce.EntityDisplayLabel == "Lead" && client.SourceSystemId == ce.ClientID);
```

**Comment by astef** [comment]
The same problem as @francnuec and @doncadavona . I'm low on space on my C: drive and an exception is thrown in the code which was previously fine:

```csharp
var user = _container.Users.FirstOrDefault(u => u.UserId == userId);
```

I am not able to reproduce it anymore on the same code and database, but I remember that this frame was on top:
`System.Data.Entity.Internal.Linq.InternalQuery'1.get_Expression() at `
