### ISSUE TITLE
Glimpse/MVC5/Sitecore Running Slowly

### ISSUE THREAD

**Issue by lakesol** [Glimpse/Glimpse#819]
We are seeing some very slow performance on our site when MVC5 support is enabled in Glimpse.  The site is Sitecore MVC5, running Glimpse for Sitecore.  However when we disable the MVC5 module normal site performance resumes.  When the module is enabled we can see very dispersed yet uniform controller actions in the timeline (see red annotation in the image).
![glimsemvc5issue](https://cloud.githubusercontent.com/assets/5919075/3508112/5d534ab0-0686-11e4-82ab-d98600690436.png)

Any thoughts on what may be causing this or how we would go about diagnosing?

Edited to add some time stats (this code is yet to be optimized/caching enabled etc)

![glimsemvc5issue2](https://cloud.githubusercontent.com/assets/5919075/3508162/254521ec-0687-11e4-8d77-d3f10c0ab020.png)

Thanks

Ian

**Comment by lakesol** [comment]
Anthony,

Ah that may be a clue, as on the site I was developing at the time, the models were being generated by Glass (http://www.glass.lu/)/  This as an ORM for sitecore, the models have the ability to lazy load all connected content.   Could the ModelBinding be trying to traverse the model thus causing lots of IO and general data operations?

**Comment by avanderhoorn** [comment]
@lakesol Yep, unfortunately this is exactly what is happening :( With Glimpse v1 as it currently is there aren't too many solutions to this problem. Most simple is just to disable the tab as you have at the moment. Or the more annoying fix, you could create a `SerializationConverter` which allows you to manually control how your models are serialized - although given your architecture, you would need almost one converter for every model - here is an [example](https://github.com/Glimpse/Glimpse/blob/master/source/Glimpse.Core/SerializationConverter/GlimpseMetadataConverter.cs) of a converter .

**Comment by Aurimas86** [comment]
It's greatly effected by EditorFor + EditorTemplate, removing ModelBinding tab reduces logged time by x10 times. But still having many EditorFor displays 2x times longer view rendering time than it's really is. I guess it's overhead of intercepting & logging every EditorFor (Let's say we have 40 of them).

**Comment by avanderhoorn** [comment]
Good catch, its an unfortunate side effect of the ModelBinding tab in some cases like this. Disabling it would be my best recommendation unless you are trying to debug something specifically,
