### ISSUE TITLE
GlimpseDbCommand nulling DbConnection during dispose #818

### ISSUE THREAD

**Issue by richardburns** [Glimpse/Glimpse#821]
I raised this issue (818) but it was closed however the fix has not resolved my issue.  Please see below:

I have installed the latest version but it doesn't change the fact that the GlimpseDbCommand when disposed of is nulling the Connection object. For example if you had the following code and used the commented out line to manually create a SqlConnection when cmd_Disposed is called then command.Connection is not null. When using the DbProviderFactory which returns a GlimpseDbConnection then then the command.Connection is null. I hope this makes sense.

```
  DbProviderFactory factory = DbProviderFactories.GetFactory("System.Data.SqlClient");
  DbConnection connection = factory.CreateConnection();
  // DbConnection connection = new System.Data.SqlClient.SqlConnection();

    using (DbCommand cmd = connection .CreateCommand())
    {
      cmd.Disposed += cmd_Disposed;
    } 

static void cmd_Disposed(object sender, EventArgs e)
{
  var command = sender as DbCommand;
  if (command == null || command.Connection == null)
    return;

  if (command.Connection.State == System.Data.ConnectionState.Open)
    command.Connection.Close();
}
```

**Comment by avanderhoorn** [comment]
@richardburns I wondering why you would manually create a new connection instead of using `CreateConnection()`?
