### ISSUE TITLE
Glimpse not recording calls from other browsers, etc

### ISSUE THREAD

**Issue by ObsidianPhoenix** [Glimpse/Glimpse#827]
I saw Anthony give an awesome talk last night, which was my first exposure to Glimpse. Today, I've been trying to use it in a webAPI project (Anthony did mention that it wasn't overly supported in the current version, so this just may not be possible).

In a basic webAPI project (newly created), with Glimpse and Glimpse.MVC4 installed, I am able to run successfully and see the call to the Default View appear in the history. Refreshing the page creates another entry in history.

However, if I try to call the same page from IE, although it loads, it does not appear in the history back in Chrome. Likewise, if I try to call an API method from within Chrome on the api, it too is not recorded.

I certainly saw Anthony show us hits from other browsers, so it's likely I'm just missing a crucial step. I have created a demo project that demonstrates this in action. To view it:

 - Run the site in Chrome and activate Glimpse.
 - Open IE and navigate to localhost:50266
 - Notice that, in Chrome, the IE call is not present
 - Navigate in Chrome to localhost:50266/api/ping (in a new tab)
 - Notice that in the original tab, the api call was not tracked.

I've uploaded the demo project to [DropBox](https://www.dropbox.com/s/fyno9dq7a3l14gu/GlimpseTest.rar) - *NB* I have deleted the packages folder to keep the download small. You will need to re-pull them via nuget.

**Comment by avanderhoorn** [comment]
@ObsidianPhoenix How did you end up going with this?

**Comment by ObsidianPhoenix** [comment]
@avanderhoorn I've mostly been working on projects that only really use a webAPI (or WCF API), without any Web UI front end lately, so I've not actually been using Glimpse.

A couple of other projects in the company are using Glimpse though, and I believe it's working pretty well for them.

If it becomes possible to hook it up to record calls to an API, this would probably be quite handy (although I don't know how you'd handle the need to have the cookie for that setup, since calls would potentially come from sources other than web pages.).

**Comment by avanderhoorn** [comment]
@ObsidianPhoenix Thanks for getting back to me. For WebAPI keep an eye out for v2.
