### ISSUE TITLE
Child application throws because of config in root application (<ignoredTypes>)

### ISSUE THREAD

**Issue by DavidDeSloovere** [Glimpse/Glimpse#837]
IIS/RootSite/SubApplication

A "Configuration Error" is thrown when the root application references a tab in it's config, but the assembly of the tab is not available in the sub application.

In web.config of root application:

    ...
    <tabs>
      <ignoredTypes>
        <add type="Glimpse.Mvc.Tab.ModelBinding, Glimpse.Mvc5" />
      </ignoredTypes>
    </tabs> 
    ...

The child application will say:

    The value of the property 'type' cannot be parsed. The error is: Could not load file or assembly 'Glimpse.Mvc5' or one of its dependencies. The system cannot find the file specified.

It would be great if **&lt;clear />** was supported for the ignoreTypes. Or the Glimpse config is wrapped in a location node with **inheritInChildApplications** set to false.

    <location path="." inheritInChildApplications="false">
      <glimpse defaultRuntimePolicy="On" endpointBaseUri="~/Glimpse.axd">
        ...
      </glimpse>
    </location>

version 1.8.6

**Comment by nikmd23** [comment]
I've added this solution to [the Troubleshooting page in our documentation](https://github.com/Glimpse/Glimpse/wiki/Troubleshooting#problem-configuration-exception-with-child-application). The new docs will go live on getGlimpse.com the next time we do an update.

**Comment by avanderhoorn** [comment]
@nikmd23 Great update!
