### ISSUE TITLE
Glimpse Panels do not display any information

### ISSUE THREAD

**Issue by mdmoura** [Glimpse/Glimpse#846]
Hello,

I added Glimpse to a MVC web site and I am able to go to Glimpse.axd and turn it on.

However, the Glimpse icon does not show. I then added @Html.GlimpseClient() to my master page.
The icon now shows, I click it, and I get the panel with the following message:
```
No data has been found. This could be caused because:
- the data is still loading by the client, or
- no data has been received from the server (check to see if the data & metadata payloads are present), or
- no plugin has been loaded, or
- an error has been thrown in the client (please check your JavaScript console and let us know if anything is up).
```
I checked for JS errors and I can't find any ...

Any idea what might be going on?

Thank You,
Miguel

**Comment by nikmd23** [comment]
Is the module, handler and Glimpse section in your `web.config`?
