### ISSUE TITLE
IE 11 Glimpse panel scroll bar under page scroll bar, can't scroll Glimpse panel

### ISSUE THREAD

**Issue by riande** [Glimpse/Glimpse#850]
![chromeff](https://cloud.githubusercontent.com/assets/3605364/4569469/cec5a58c-4f4a-11e4-9068-3d83dc70595f.jpg)
![iescroll](https://cloud.githubusercontent.com/assets/3605364/4569470/d0c59694-4f4a-11e4-9173-ebdfc5e5f572.png)
In IE 11, the page scroll bar and Glimpse panel scroll bar are in the same place, so the Glimpse panel scroll bar never gets events to scroll. (see pic's).

Work around:
1. Scroll with the scroll wheel.
2. Use FF or Chrome.

To repro.
1. Create a new MVC project and Add/enable Glimpse.
2. Click on the execution tab - make the window small enough you need to scroll.

**Comment by nikmd23** [comment]
I've just tested this in IE11, and it seems like this problem has been fixed as of at least version 1.8.4 of Core.
