### ISSUE TITLE
MVC upgraded from 4 to 5. Access denied javascript error

### ISSUE THREAD

**Issue by sscoleman** [Glimpse/Glimpse#851]
It loads on the index page and contact.   I've posted on stackoverflow. Because it would not show me the preview for my images.  
http://stackoverflow.com/questions/26270749/glimpse-mvc-4-upgraded-to-5-javascript-error-access-denied-on-page-change

**Comment by nikmd23** [comment]
I've added a comment on your StackOverflow question @sscoleman. I'm going to close this issue in favor of the one there.
