### ISSUE TITLE
Glimpse v2 - OWIN/vNext Samples

### ISSUE THREAD

**Issue by avanderhoorn** [Glimpse/Glimpse#853]
Before we release a v2 CTP, it would be ideal if we had verification of things working on OWIN/vNext outside of just simple hello world samples. 

**OWIN:**
A thought would be to use this [sample](https://github.com/NancyFx/Nancy.Demo.Samples) (it will need updating to the latest version of nancy) and convert the host over to OWIN using the information [here](https://github.com/NancyFx/Nancy/wiki/Hosting-nancy-with-owin). If we did this, I think we would have enough to verify successful OWIN hosting.

**vNext:**
The ASP.NET maintains two sample applications: [Music Store](http://www.asp.net/vnext/overview/aspnet-vnext/walkthrough-mvc-music-store) and [ButTracker](http://www.asp.net/vnext/overview/aspnet-vnext/walkthrough-bugtracker). I'm not sure which is best, but assuming they are both good enough, prefer Music Store.

**Comment by Daniel15** [comment]
Has there been any further work on getting Glimpse to run on ASP.NET 5?

**Comment by avanderhoorn** [comment]
Take a look at the Glimpse.Prototype repo :) -
https://github.com/Glimpse/Glimpse.Prototype

**Comment by Daniel15** [comment]
I did see that repo but wasn't sure if it was ready for use yet.

**Comment by mcquaiga** [comment]
Has anyone had success running Glimpse on OWIN with .NET 4.5?

I have a WebAPI backend running on top of OWIN and a Javascript/Knockout frontend that I'd like to get Glimpse integrated into. Can you point me towards any examples of a similar architecture? If not, is there any way I can help?

**Comment by rfcdejong** [comment]
I just tried to use Glimpse on OWIN, but it seems the pull request did not went thru. Currently I don't see a way to use Glimpse on OWIN, the branch code seems to be too far behind as well.
