### ISSUE TITLE
Public access to InnerDataAdapter on GlimpseDbDataAdapter

### ISSUE THREAD

**Issue by Peluko** [Glimpse/Glimpse#861]
Hello.

I've managed to get Glimpse working on one of our applications. It's a somewhat large application with lots of old code that must work along with the new code. I've wrapped our Sql Server connections with Glimpse.ado and it's working ok.
One problem I had to face was that I need access to the `SqlDataAdapter.RowUpdated` event. This event isn't defined on the generic `DbDataAdapter` interface so it's not exposed by `GlimpseDbDataAdapter`. The solution is to have access to the `InnerDataAdapter` property of `GlimpseDbDataAdapter`, but it's defined as private. I've managed to do so by using reflection, but I think that it should be public, so I (and other potential users) can guarantee that it won't change/rename/disappear on future release.

Regards.

**Comment by avanderhoorn** [comment]
@Peluko Is this something that would still be useful to you?

**Comment by avanderhoorn** [comment]
I think this was done.
