### ISSUE TITLE
Seek definitive guide to configuring Glimpse and Azure Website

### ISSUE THREAD

**Issue by justSteve** [Glimpse/Glimpse#867]
I've seen a couple threads on Stackoverflow (re: configuration requirements for Glimpse via an Azure Website) but nothing approaches a global, comprehensive solution. Does such exist?

thx

**Comment by maartenba** [comment]
I think its basically like setting up Glimpse for any website?
Or are you referring to the Glimpse Azure plugins? http://blog.maartenballiauw.be/post/2013/12/30/Introducing-Glimpse-plugins-for-Windows-Azure.aspx

**Comment by avanderhoorn** [comment]
@justSteve Have you had any chance to circle back on this one?

**Comment by nikmd23** [comment]
I think @justSteve is just wondering how to run Glimpse on a remote server. (Azure Websites in his example.)

@justSteve while we don't mention Azure specifically in the docs, [the Running Remotely section of our Runtime Policies documentation](http://getglimpse.com/Docs/Runtime-Policies) outlines everything you need to know.
