### ISSUE TITLE
Glimpse is misreporting that it's out of date

### ISSUE THREAD

**Issue by DanAtkinson** [Glimpse/Glimpse#868]
Hi there,

Glimpse is reporting that it's out of date when it clearly isn't.

I have a [screengrab](http://i.imgur.com/xkiRDZb.png) from glimpse.axd which shows the yellow warning bar, but it also shows the version numbers of the relevant modules being used.

Namely:
* Glimpse.AspNet (1.9.2)
* Glimpse (1.8.6)
* Glimpse.Mvc4 (1.5.3)

Note that these are all the latest versions as of Wednesday 7th January 2015.

However, when I go to the 'See what you're missing out on' [page](http://getglimpse.com/version/check?Glimpse.AspNet=1.9.1&Glimpse=1.8.6&Glimpse.Mvc4=1.5.3), the versions in the url suggest that Glimpse.AspNet is actually 1.9.1 ([screengrab](http://i.imgur.com/vDyS5cX.png)).

This doesn't make a lot of sense to me as, in the same page, it shows that the loaded Glimpse.AspNet module is 1.9.2, but the hyperlink to the update page suggests otherwise.

I've done the usual incantations (restart IIS, clear cookies, empty solution, rebuild, republish, turn computer off and on, try on a clean machine) but I'm still seeing the same misreporting error.

I am running on Windows 7, ASP.NET 4.0 with MVC v4 on IIS 7.5.

The Glimpse.log file doesn't contain much of note:

> 2015-01-07 13:33:46.7606 | DEBUG | RuntimePolicy set to 'Off' by IRuntimePolicy of type 'Glimpse.Core.Policy.ControlCookiePolicy' during RuntimeEvent 'BeginRequest'. | 
> 2015-01-07 13:33:46.7606 | DEBUG | RuntimePolicy set to 'ExecuteResourceOnly' by IRuntimePolicy of type 'Glimpse.Core.Policy.GlimpseResourcePolicy' during RuntimeEvent 'ExecuteResource'. | 
> 2015-01-07 13:33:47.0266 | DEBUG | RuntimePolicy set to 'Off' by IRuntimePolicy of type 'Glimpse.Core.Policy.ControlCookiePolicy' during RuntimeEvent 'BeginRequest'. | 
> 2015-01-07 13:33:47.0266 | DEBUG | RuntimePolicy set to 'ExecuteResourceOnly' by IRuntimePolicy of type 'Glimpse.Core.Policy.GlimpseResourcePolicy' during RuntimeEvent 'ExecuteResource'. | 
> 2015-01-07 13:33:47.0266 | DEBUG | RuntimePolicy set to 'Off' by IRuntimePolicy of type 'Glimpse.Core.Policy.ControlCookiePolicy' during RuntimeEvent 'BeginRequest'. | 
> 2015-01-07 13:33:47.0266 | DEBUG | RuntimePolicy set to 'Off' by IRuntimePolicy of type 'Glimpse.Core.Policy.ControlCookiePolicy' during RuntimeEvent 'BeginRequest'. | 
> 2015-01-07 13:33:47.0266 | DEBUG | RuntimePolicy set to 'ExecuteResourceOnly' by IRuntimePolicy of type 'Glimpse.Core.Policy.GlimpseResourcePolicy' during RuntimeEvent 'ExecuteResource'. | 
> 2015-01-07 13:33:47.0266 | DEBUG | RuntimePolicy set to 'ExecuteResourceOnly' by IRuntimePolicy of type 'Glimpse.Core.Policy.GlimpseResourcePolicy' during RuntimeEvent 'ExecuteResource'. | 
> 2015-01-07 13:33:47.0436 | DEBUG | RuntimePolicy set to 'Off' by IRuntimePolicy of type 'Glimpse.Core.Policy.ControlCookiePolicy' during RuntimeEvent 'BeginRequest'. | 
> 2015-01-07 13:33:47.0436 | DEBUG | RuntimePolicy set to 'ExecuteResourceOnly' by IRuntimePolicy of type 'Glimpse.Core.Policy.GlimpseResourcePolicy' during RuntimeEvent 'ExecuteResource'. | 
> 2015-01-07 13:33:47.0436 | DEBUG | RuntimePolicy set to 'Off' by IRuntimePolicy of type 'Glimpse.Core.Policy.ControlCookiePolicy' during RuntimeEvent 'BeginRequest'. | 
> 2015-01-07 13:33:47.0436 | DEBUG | RuntimePolicy set to 'ExecuteResourceOnly' by IRuntimePolicy of type 'Glimpse.Core.Policy.GlimpseResourcePolicy' during RuntimeEvent 'ExecuteResource'. | 

Thanks, Dan

**Comment by avanderhoorn** [comment]
@DanAtkinson Is it still reporting that it is out of date? I suspect that the issue is around the fact that we only check for updates once a day (or every few days - can't remember off the top of my head). This means that the following can occur:
 - You open up Glimpse in the morning
 - Glimpse checks to see if it is out of date
 - Glimpse records whether it is out of date and stores/caches the result locally for `x`hrs
 - Once Glimpse has conducted that first check after the `x`hrs has gone, it wont check again for another `x`hrs
 - Any time Glimpse render during the `x`hrs window, **it will report report the cached status**

This workflow/logic means that it is possible that Glimpse will report that it is out of date even though you have just done an update. I've racked my brain around how we can avoid this false positive window of reporting, but it's a really tough problem to crack since any solution requires the client to know that your project has just been updated or for us to do more aggressive.

Do you have any thoughts about what we could do better here given the about context?

**Comment by DanAtkinson** [comment]
@avanderhoorn Hi.

I can confirm that caching seems to be the likeliest culprit here as a refresh no longer shows the warning. Although why exactly it (version number) is needed here since at least _some_ of the page displays correct values as shown in this [screengrab](http://i.imgur.com/xkiRDZb.png) - correct module version, incorrect link.

Surely, if we're able to determine that the loaded DLL is of the correct version _before_ the page is loaded, then we should be able to show/hide the out of date warning.

Thanks.

**Comment by nikmd23** [comment]
@DanAtkinson,

Did this problem go away for you? We cache the version checking pretty aggressively (for performance reasons), but incorrect reports usually go away within a day or so.

**Comment by DanAtkinson** [comment]
Hi there,

It went away, yes, but surely a version update + rebuild should have triggered a cache flush?

Do you not compare the loaded DLL version against the cached version number on application start? I think that this bug probably would have been avoided with this simple check. :)

Thanks, Dan

**Comment by nikmd23** [comment]
@DanAtkinson it's actually cached in your browser. Clearing that cache would have fixed the problem. :wink:

**Comment by avanderhoorn** [comment]
As you can tell from the screen grab, its not determining the version number that is the issue, if performing the check, I'll try to explain. As you can see, Glimpse is made up of multiple dll's, each of which have their own version numbers. When the client performs the version check, it actually has no concept of what versions are at play or how the check is performed. 

The key here is that the client doesn't perform the check directly. The client actually calls the Glimpse code hosted in your app, which in tern works out which versions of which packages are at play and forwards the request onto the version check service. Hence the client doesn't have any concept of packages, versions, etc. It just knows whether the result returned out of date or not. 

We probably could do a version check every time you go to the `/glimpse.axd` page, but that is something we haven't done to date as we have wanted to avoid doing any more calls to the version check service than needed. We could also probably enhance the client to have more knowledge of packages and versions, but currently the one client can work across php, node, etc... not all these platforms have the same versioning semantics. Hence why the client defers to the server to do the processing. Does that make sense?

**Comment by DanAtkinson** [comment]
@avanderhoorn @nikmd23 Hi both.

It makes sense. I think going to the external service every time that `glimpse.axd` is loaded might be overkill, but I guess that depends on how often that page is hit. Usually, I only go to `glimpse.axd` when I'm turning it on/off.

**Comment by avanderhoorn** [comment]
@DanAtkinson How often is that? Trying to get a sense of what might be an acceptable interval. Another thing we could do is add a manual refresh button to that status message, but that fells more like a hack than a solution.

**Comment by DanAtkinson** [comment]
@avanderhoorn For me, once a day is how often I hit glimpse..axd, to switch it on. And then I spend the rest of the day using the day using the in-page dashboard. I don't know if you have any analytics tracking this page usage or not, but that might give you a better idea.

Thanks, Dan

**Comment by CGijbels** [comment]
@DanAtkinson if you move those on/off button to your browser's bookmarks toolbar, then you have bookmarklets that you can use and you don't need to go to the glimpse.axd any longer. 

@avanderhoorn Maybe we need to promote the bookmarklets a little bit more? Either way, an explicit refresh button doesn't seem like a real hack to me, because users don't really know how that status message is built and certainly not that it is being cached, so a force refresh or better a _please check it again, they ought to be up-to-date_ kind of button might be useful

**Comment by avanderhoorn** [comment]
@CGijbels That could be a good idea on all fronts.
