### ISSUE TITLE
Glimpse adds additional <httpHandlers> element in web.config during installation when <location> element is present

### ISSUE THREAD

**Issue by rugved** [Glimpse/Glimpse#869]
Hi,

In my web.config I have location element on top of my system.web element with inheritInChildApplications set to "false"

  > <location path="." inheritInChildApplications="false">
 >  <system.web>
  >   <httpHandlers>
 >        <add verb="*" path="routes.axd" type="AttributeRouting.Web.Logging.LogRoutesHandler, > AttributeRouting.Web" />
 >    </httpHandlers>
> ...

in this case, during installation Glimpse inserts its own System.web at the bottom

<system.web>
        <httpModules>
            <add name="Glimpse" type="Glimpse.AspNet.HttpModule, Glimpse.AspNet" />
        </httpModules>
        <httpHandlers>
            <add path="glimpse.axd" verb="GET" type="Glimpse.AspNet.HttpHandler, Glimpse.AspNet" />
        </httpHandlers>
    </system.web>

**Comment by avanderhoorn** [comment]
@rugved Did you end up fixing your issue?
