### ISSUE TITLE
Glimpse Showing Traffic From Other User Without Access Glimpse.axd 

### ISSUE THREAD

**Issue by smehaffie** [Glimpse/Glimpse#870]
In our company we would want to only allow our IIS administers to turn on Glimpse and generate the cookie.  But if on we would want all user traffic to be recorded. Basically, allow one person to turn on Glimpse, but the allow any other browser hitting the site see that Glimpse has been turned on and create the cookie for the new session (as if they had turned it on).  Then when an IIS admin turns it off the other sessions would need to know that and delete the cookie that was created for their session. This would also need to work across load balanced servers.

We do have a configuration database that we could put a setting for the application to turn Glimpse on or off.  So if there is no way to do implement this out of the box, would there be a way that on each new request we look at a configuration value and then based on that turn Glimpse on/off though code?

**Comment by nikmd23** [comment]
Hi @smehaffie,

You can configure Glimpse to run/not run in any way you'd like by leveraging [a runtime policy](http://getglimpse.com/Docs/Runtime-Policies).

In your described case, I'd recommend disabling the default cookie policy, which means edditing `web.config` to look like this:

```xml
<glimpse defaultRuntimePolicy="On" endpointBaseUri="~/Glimpse.axd">
    <runtimePolicies>
        <ignoredTypes>
            <add type="Glimpse.Core.Policy.ControlCookiePolicy, Glimpse.Core"/>
        </ignoredTypes>
    </runtimePolicies>
</glimpse>
```

Then you should add a [custom runtime policy](http://getglimpse.com/Docs/Custom-Runtime-Policies) which looks in your configuration database. It might work something like this:

```csharp
using Glimpse.AspNet.Extensions;
using Glimpse.Core.Extensibility;

namespace Users.Web.Application.Namespace
{
    public class GlimpseSecurityPolicy:IRuntimePolicy
    {
        public RuntimePolicy Execute(IRuntimePolicyContext policyContext)
        {
            if (!ConfigDatabase.GlimpseEnabled)
                return RuntimePolicy.Off;

            return RuntimePolicy.On;
        }

        public RuntimeEvent ExecuteOn
        {
            get { return RuntimeEvent.EndRequest; }
        }
    }
}
```
