### ISSUE TITLE
Glimpse.ADO not working with Oracle Data Provider

### ISSUE THREAD

**Issue by corte** [Glimpse/Glimpse#871]
Hi,

I'm trying to use Glimpse.ADO with Oracle Data Provider and I'm getting a conversion error:
> Unable to cast object of type 'Glimpse.Ado.AlternateType.GlimpseDbConnection' to type 'Oracle.DataAccess.Client.OracleConnection'. 

I'm using Entity Framework and this error happens in the following code:
```c-sharp
        public string GetParameter(string parameter, long lineId)
        {
            var entityConnection = (System.Data.EntityClient.EntityConnection)this.Connection;
            OracleConnection conn = (OracleConnection)entityConnection.StoreConnection; // Error thrown in this line

            ConnectionState initialState = conn.State;

            try
            {
                if (initialState != ConnectionState.Open)
                    conn.Open();  // open connection if not already open 
                using (OracleCommand cmd = conn.CreateCommand())
                {
                    cmd.CommandText = "PARAMETERS.GET";
                    cmd.CommandType = CommandType.StoredProcedure;

                    OracleParameter retVal = new OracleParameter("vRetVal", OracleDbType.Varchar2, 512);
                    retVal.Direction = ParameterDirection.ReturnValue;

                    cmd.Parameters.Add(retVal);
                    cmd.Parameters.Add("pCode", parameter);
                    cmd.Parameters.Add("pLine", lineId);

                    cmd.ExecuteNonQuery();

                    return ((INullable)retVal.Value).IsNull ? "" : retVal.Value.ToString();
                }
            }
            finally
            {
                if (initialState != ConnectionState.Open)
                    conn.Close(); // only close connection if not initially open 
            }
        }
```

I've installed the following Nuget packages:
* Glimpse - Version: **1.8.6**
* Glimpse.AspNet - Version: **1.9.2**
* Glimpse.Ado - Version: **1.7.3**
* Glimpse.EF43 - Version: **1.6.5**

Please, can you help me solve this issue?

**Comment by corte** [comment]
Hi again,

I've managed to make it work changing a little bit the code:
```     
        public string GetParameter(string parameter, long lineId)
        {
            var entityConnection = (System.Data.EntityClient.EntityConnection)this.Connection;
            DbConnection conn = entityConnection.StoreConnection; // Error thrown in this line

            ConnectionState initialState = conn.State;

            try
            {
                if (initialState != ConnectionState.Open)
                    conn.Open();  // open connection if not already open 
                using (DbCommand cmd = conn.CreateCommand())
                {
                    cmd.CommandText = "PARAMETERS.GET";
                    cmd.CommandType = CommandType.StoredProcedure;

                    OracleParameter retVal = new OracleParameter("vRetVal", OracleDbType.Varchar2, 512);
                    retVal.Direction = ParameterDirection.ReturnValue;

                    cmd.Parameters.Add(retVal);
                    cmd.Parameters.Add(new OracleParameter("pCode", parameter));
                    cmd.Parameters.Add(new OracleParameter("pLine", lineId));

                    cmd.ExecuteNonQuery();

                    return ((INullable)retVal.Value).IsNull ? "" : retVal.Value.ToString();
                }
            }
            finally
            {
                if (initialState != ConnectionState.Open)
                    conn.Close(); // only close connection if not initially open 
            }
        }
```

After that I realized that I could simply do:
```
        public string GetParameter(string parameter, long? lineId = null)
        {
            string sql = "SELECT PARAMETER.GET(:pCode, :pLine) FROM DUAL";
            return ExecuteStoreQuery<string>(sql, parameter, (lineId.HasValue ? lineId : null)).FirstOrDefault();
        }
```

Everything is working fine now, but it would be good to have this fixed.

Thank you.

**Comment by avanderhoorn** [comment]
@corte I'm a little perplexed. The code above doesn't look like code in Glimpse. Any chance you can link me to the code?

**Comment by corte** [comment]
@avanderhoorn Sorry, actually it's not a code in Glimpse.

This is only the call using oracle data provider. I don't know how Glimpse works, but I started having this issue right after installing Glimpse through Nugget.

I think the real problem is that I was using the Entity Framework connection to do this. I've tried with a simple code using only ODP.net and it worked.

**Comment by corte** [comment]
Hmm..
Now I see what the problem really is.

Glimpse in someway converts my EntityFramework connection to an object of GlimpseDbConnection. When getting the entity framework connection with 
```
((System.Data.EntityClient.EntityConnection)this.Connection).StoreConnection
```
I had an GlimpseDbConnection object and then I was trying to convert it to an OracleConnection in order to use it to call stored procedures in my database.

I guess it was my mistake then. :)

**Comment by avanderhoorn** [comment]
@corte now I understand :) The Glimpse ADO insights works by wrapping the various DbProviderFactories. This means that when Glimpse is running and you get a result from anything using the DbProviderFactories (like `this.Connection` or `conn.CreateCommand()`) the results are going to be Glimpse types. 

In theory this is fine as DbProviderFactories only says that it is going to return you types that inherit from `DbConnection`, `DbCommand`, etc, but in practice there are times (like this one) where you might need to do some casting to access specific features. That said, under normal circumstances you shouldn't have to do any castings - again unless there is a really good reason why; which this might be. 

I would encourage you to look at your code and see if there is a way you can do what you are doing without casting. If not, then you might introduce an `as` check to verify the type first (so you know if Glimpse is a play or not). Otherwise, there are other work arounds, they are just more work. Let me know if the current/suggested work arounds work for you or if you want something different. Hope this makes sense and helps.
