### ISSUE TITLE
Glimpse.Mvc4 breaks Umbraco routing

### ISSUE THREAD

**Issue by ViktorBergman** [Glimpse/Glimpse#875]
Not sure on where to take this, umbraco or Glimpse but I'll give it a shot here. When installing Glimpse.Mvc4 into an umbraco 7 site all links breaks, probably due to the routing. If I remove Glimpse.Mvc4, hence only running Glimpse.Aspnet and core, it all works. But then I'm missing what I was after in the first place: action execution statistics.
Kind regards,
Viktor

**Comment by nikmd23** [comment]
I'm not really sure if this is something we can fix or not, but do you have the errors that are generated? Or is it that there is no errors, the link are just pointing to the wrong URLs?
