### ISSUE TITLE
fetch and execute client scripts in another website

### ISSUE THREAD

**Issue by awerlang** [Glimpse/Glimpse#876]
I have an SPA that have a WebApi back-end, Glimpse enabled. I like to show HUD in my SPA. Actually, I'm able to do it and it works like a charm, but I have two concerns.

1) I need to retrieve a `requestId` from WebApi. As I don't have any page, I make a request to Elmah.axd (the only HTML request i can think of). Requesting Glimpse.axd doesn't work. There's a better way to access `requestId`?

2) What is `hash` in query string? I have just hardcoded one from a manual request.

Thanks in advance.

```js
var ajax = function (url, successFn) {
    var request = new XMLHttpRequest();
    request.open('GET', url);
    request.onload = function () {
        if (request.status >= 200 && request.status < 400) {
            successFn && successFn.call(request);
        }
    };
    request.send();
};
ajax('/api/elmah.axd', function () {
    var requestId = this.getResponseHeader("Glimpse-RequestID");
    var glimpseUrl = '/api/Glimpse.axd?n=glimpse_request&requestId=' + requestId + '&hash=2e34b611&callback=glimpse.data.initData';
    ajax(glimpseUrl, function () {
        var globalEval = eval;
        globalEval(this.responseText);
    });
});
```

**Comment by nikmd23** [comment]
@awerlang, I don't think that this works the way you think it does. 

You're JS code is getting the request ID for the request made to elmah.axd. So you're really just getting/showing what happened on the request that you just forced.

Can you describe what you're trying to accomplish a bit more? That should help us point you in the right direction.

**Comment by awerlang** [comment]
@nikmd23 If I were running an MVC site, HUD would display XHR's made to its backend. Client and server are running on the same webapp.

I don't know how popular this approach is among Glimpse users, but I need to show XHR's made from webapp A to webapp B. I don't care about requests to webapp, it's just partials.

I make a request to any page on webapp (elmah.axd,in this case, and actually I'm doing a HEAD in my code). It needs to be a non-XHR request to some HTML. I really don't care what happens in this request. But I get access to Glimpse-RequestID header.

I make a second request, this time to glimpse.axd to bootstrap glimpse's client scripts on webapp A. It's crucial to pass the token received from the last request. Thereafter, all XHR from webapp A to webapp B are brought to HUD.

Does it makes sense? 

I'd like to package this code and publish, but then I have two concerns I pointed in this issue

**Comment by CGijbels** [comment]
Just a hunch, but I think @awerlang is trying to open up the Glimpse panel as his first page isn't loading Glimpse and all the rest are Ajax calls inside his SPA.
I've seen this demand previously and have encountered this _issue_ before. There needs to be an easy way to open up the Glimpse client, so that you can look at all the requests being traced through the history and ajax tabs for instance.

Currently you need a requestId to be able to open up the Glimpse panel in popup mode, so I guess that is the reason why @awerlang is faking a request just to get a valid request id.

The HUD is only a means to get to the panel, but from a SPA point of view it wouldn't offer any advantage as it would only show the first request made, which is most likely the index page setting up the SPA application to begin with.

I might be wrong as well :wink:

**Comment by CGijbels** [comment]
I knew I mentioned it somewhere before => [it's over here](https://github.com/Glimpse/Glimpse/issues/715#issuecomment-33830125) and @avanderhoorn agreed :wink: 
it is still on the todo list unfortunately

**Comment by CGijbels** [comment]
and yes @nikmd23 I know I could have fixed that a long time ago as well :blush:

**Comment by awerlang** [comment]
@CGijbels 

> The HUD is only a means to get to the panel, but from a SPA point of view it wouldn't offer any advantage as it would only show the first request made, which is most likely the index page setting up the SPA application to begin with.

Nope, it captures all requests from that point on. 

I don't have Glimpse installed on my SPA. If I do that, then it would happen what you just said.

**Comment by CGijbels** [comment]
@awerlang you mean it shows you that there were Ajax calls made? But the _http_ and _host_ tab of the HUD remain unaffected by subsequent Ajax calls and only keeping the HUD for Ajax notifications seems overhead no?

You want to trap Ajax requests made on application B and want to have the HUD in your SPA to show those requests? 

Therefore I wonder that if you would be able to open the Glimpse Client by means of navigating to the Glimpse.axd on application B (which has Glimpse installed I presume) than that would solve your problem? Or am I still missing something here?

**Comment by awerlang** [comment]
@CGijbels I think I'm maybe missing something. In a normal setup, what's the use case for HUD, instead of using Glimpse.axd standalone?

At least for me it is just more convenient to use HUD.

**Comment by CGijbels** [comment]
@awerlang ah, ok, so basically this is what you get when you have Glimpse activated

When you make a request to a page, the response contains the Glimpse client which initially will show up as the HUD 
![image](https://cloud.githubusercontent.com/assets/1467346/6047196/6b1b9288-aca8-11e4-8589-ff03b0585e79.png)
  
the _http_ and _host_ tab in the HUD show summarized data for that particular request only, while the _ajax_ tab only indicates 0 ajax requests

if you would have some Ajax calls (known by Glimpse) while that page is open, then they will start to show up in the HUD as follows
![image](https://cloud.githubusercontent.com/assets/1467346/6047233/b644f290-aca8-11e4-8022-1245a5327e47.png)
and you will be able to go to more detailed information of a particular Ajax request by clicking on it
![image](https://cloud.githubusercontent.com/assets/1467346/6047278/f5ad41b2-aca8-11e4-8597-aeea4bf43688.png)

Aside from the Ajax calls, when you click on the Glimpse icon in the lower right corner, it will show you the Glimpse panel, containing all the information gathered during the first initial request that returned you the HUD with the Glimpse Client in the first place
![image](https://cloud.githubusercontent.com/assets/1467346/6047333/6bc82060-aca9-11e4-9ec9-e5ca870dc34d.png)

As you can see there is an _Ajax_ tab and a _History_ tab, the _Ajax_ tab is basically a subset of the requests (only those indicated as an Ajax call) that you can see in the History tab.

Those tabs allow you to inspect other requests to see the information that has been traced while those requests were being processed:
![image](https://cloud.githubusercontent.com/assets/1467346/6047396/db2246f2-aca9-11e4-8732-dba660f21fb2.png)

The client is a grouping based on a session name that you can define yourself through the Glimpse.axd and if none is defined it will base the name on the browser being used.
And on the right you'll see the requests that have been made in a particular _session_. Those requests can have been made before you loaded your page and/or after, as long as they can be found in the Glimpse Request store (out-of-the-box this is a rolling memory store). Once you inspect a specific request, the whole panel will change and you'll see in the title bar which request is active. This means that if you take a look at one of those tabs like _Request_ for instance, then you'll see the information as it was for that particular request, no longer for the original request that loaded the HUD and the Glimpse Client
![image](https://cloud.githubusercontent.com/assets/1467346/6047520/7b2df312-acaa-11e4-930e-bb85b87643ad.png)

By clicking on _Original_ you can return to the original data view of the request that loaded the HUD etc...

There is another option in the right top corner of the Glimpse client which allows you to load that Glimpse Client panel as a popup
![image](https://cloud.githubusercontent.com/assets/1467346/6047575/d895a9f0-acaa-11e4-8562-cfdebe5af168.png)

From then on you can use that popup to read the data of requests going on, even when pages are being refreshed or are not returning the Glimpse Client to begin with.

Therefore the idea that I mentioned above, was to be able to load the popup without the need to start from an existing traced request. That way you can configure Glimpse to never return the Glimpse Client as part of the response, yet you're still able to see the panel.

I hope the above makes sense and that you can see how it can/cannot work for your issue?

**Comment by avanderhoorn** [comment]
As a side note, for SPA apps, I made a change a few releases to `/Glimpse.axd` which when you go there is a button to launch Glimpse client in the popup mode with the last request selected. Once opened, you should be able to use the history tab to find any requests, etc.

**Comment by CGijbels** [comment]
@avanderhoorn awesome, I didn't know  the popup no longer required a request id to launch. Lets mark that as done on the todo list :wink:

**Comment by avanderhoorn** [comment]
@CGijbels sounds good :D

@awerlang has this worked for you?

**Comment by awerlang** [comment]
yep, it works!

**Comment by avanderhoorn** [comment]
Great!
