### ISSUE TITLE
What about normal Glimpse releases as ever plus "GlimpseSN" (strong named) releases?

### ISSUE THREAD

**Issue by gingters** [Glimpse/Glimpse#879]
Hello,

I want to bring up the discussion about strong naming once gain.

First of all, I know that it was planned to release Glimpse 1.0 strong named, and this has been changed after this discussion: https://groups.google.com/forum/?fromgroups=#!topic/getglimpse-dev/pXXazMOOdjE

Almost two years ago this issue here was closed in reference to the above stated discussion: https://github.com/Glimpse/Glimpse/issues/324

It mainly boiled down to the point where it was said that it may impose a little annoyance to some users when strong naming the assemblies, which should not be done, while all others really requiring a strong name could take the source and build it strong named for their own use.

Now, we internally are switching to strong name our assemblies, this decision hits us. Thing is: We cannot go the route to keep track of glimpse and all updates and releases an maintain our own fork just to have a strong named assembly of it. Its simply too much effort, as our own libraries are used by several other projects and which want/need to update Glimpse on their own, which will make using Glimpse impossible for us in the future.

This is why I want to bring up this question:

What about releasing two official versions of Glimpse in the future?
Keep everything as it is, but with every future release, also build an additional second, signed version of all Glimpse packages and publish them as additional GlimpseSN.* packages.

My take on this is:
* This can be automated, so it's a one-timer to set this up
* It does not affect any current user of the unsigned versions in any way
* It makes things a lot easier for people currently signing them on their own, as they (and we :) ) can simply use NuGet again in the future

Your opinion?
If you could think of this, we could (and also would) jump in and make sure that all dependencies Glimpse has are also strong named, and get in touch with you to make that as painless as possible. This is in fact a lot more efficient for us than to manage our own strong named fork all along the projects progress.

**Comment by nikmd23** [comment]
@gingters,

Thanks for you're continued use and perspective on Glimpse. We've always been happy to have you as a passionate user who is always trying to make the platform better.

Here's my take:

You're right, this could be set up to be automated, and once that work is done this is pretty easy to achieve going forward.

Here's my proposal (others, please chime in): if you'd like to setup the build file to do this, so that the signed packages get pushed to a special MyGet feed, I'm cool with it. I'd have concerns about putting the signed packages on NuGet.org - but if you don't mind adding an additional package source to your configuration then this should work well.

Thoughts?

**Comment by CGijbels** [comment]
@gingters Either way I feel somewhat sorry for you that they internally decided to switch to strong naming those assemblies, knowing that everybody, including MS is moving away from this path. One can only hope security is not the motivator

@nikmd23 @gingters Have a look at [this post - Automatically-strong-name-signing-NuGet-packages](http://blog.maartenballiauw.be/post/2014/09/10/Automatically-strong-name-signing-NuGet-packages.aspx) by @maartenba , it might help creating those signed assemblies even easier

**Comment by gingters** [comment]
@nikmd23 Of course myget is okay for us too.

@CGijbels Security is somewhat the motivator. We are required to make our things temper-safe(r) or at least a lot more difficult to temper with them. We had things happen in the past, that really would make people shudder.

From the about 90 external references Glimpse currently has (wow, by the way, that's a lot!), only 2 are not strong named.

First, we will investigate the automatic strong naming of nuget packages. Thanks @CGijbels for that info. That might safe us a lot of additional efforts and mabe make this endevour a very short trip. If that does not work, however, we're going to get the two dependencies strong named, and then Glimpse :)

I will update you with further info on the progress.

**Comment by nikmd23** [comment]
Awesome, thanks @gingters.

I'm going to close this issue for now then. If/when you have something ready for us to look at, please open up a pull request.
