### ISSUE TITLE
Glimpse handler not found (Glimpse.1.8.6 + Glimpse.AspNet.1.9.2 + NHibernate.Glimpse.3.3.3.40011)

### ISSUE THREAD

**Issue by soledadtctvtn** [Glimpse/Glimpse#880]
Hi all,

I've setup with below settings on my project:
- MVC3
- Glimpse.1.8.6
- Glimpse.AspNet.1.9.2
- NHibernate.Glimpse.3.3.3.40011
- Nhibernate vs ODAC - Oracle DataAccess Client (Enable 32 bit Application on App-pool)

But Glimpse.axd not found eventhough scripts is generated at the bottom of my page. Any help???

**Comment by avanderhoorn** [comment]
So when you go to `/glimpse.axd` what error do you get?

**Comment by nikmd23** [comment]
Also, what's in the `httpHandlers` section of your `web.config`?

**Comment by soledadtctvtn** [comment]
@avanderhoorn : Launch /Glimpse.axd take me to my custom 404 page error (see below my config)
@nikmd23 : Please view my little config (excluding my app config):

  <configSections>
    <section name="glimpse" type="Glimpse.Core.Configuration.Section, Glimpse.Core" />
  </configSections>

  <appSettings>
    
    <add key="webpages:Version" value="1.0.0.0"/>
    <add key="ClientValidationEnabled" value="true"/>
    <add key="UnobtrusiveJavaScriptEnabled" value="true"/>
  </appSettings>
  <system.web>
    <compilation debug="false" targetFramework="4.0">
      <assemblies>
        <add assembly="System.Web.Abstractions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" />
        <add assembly="System.Web.Helpers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" />
        <add assembly="System.Web.Routing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" />
        <add assembly="System.Web.Mvc, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" />
        <add assembly="System.Web.WebPages, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" />
      </assemblies>
    </compilation>
    <pages>
      <namespaces>
        <add namespace="System.Web.Helpers" />
        <add namespace="System.Web.Mvc" />
        <add namespace="System.Web.Mvc.Ajax" />
        <add namespace="System.Web.Mvc.Html" />
        <add namespace="System.Web.Routing" />
        <add namespace="System.Web.WebPages"/>
      </namespaces>
    </pages>
    <sessionState mode="InProc" timeout="120" />
    
    <httpRuntime maxRequestLength="563200"/>
    <globalization culture="en-US" uiCulture="en" responseEncoding="utf-8" />
    
    <httpModules>
      <add name="Glimpse" type="Glimpse.AspNet.HttpModule, Glimpse.AspNet" />
    </httpModules>
    <httpHandlers>
      <add path="glimpse.axd" verb="GET" type="Glimpse.AspNet.HttpHandler, Glimpse.AspNet" />
    </httpHandlers>
  </system.web>
  <system.webServer>
    <security>
      <requestFiltering>
        
        <requestLimits maxAllowedContentLength="576716800" />
      </requestFiltering>
    </security>
    <validation validateIntegratedModeConfiguration="false"/>
    <modules runAllManagedModulesForAllRequests="true">
      <remove name="WebDAVModule" />
      <add name="Glimpse" type="Glimpse.AspNet.HttpModule, Glimpse.AspNet" preCondition="integratedMode" />
    </modules>
    <handlers accessPolicy="Read, Write, Execute, Script">
      <remove name="StaticFile" />
      <remove name="SimpleHandlerFactory-ISAPI-2.0" />
      <remove name="WebDAV" />
      <remove name="SimpleHandlerFactory-Integrated-4.0" />
      <remove name="SimpleHandlerFactory-Integrated" />
      <add name="SimpleHandlerFactory-Integrated" path="*.ashx" verb="GET,HEAD,POST,DEBUG,PUT,DELETE" type="System.Web.UI.SimpleHandlerFactory" resourceType="Unspecified" requireAccess="Write" preCondition="integratedMode" />
      <add name="SimpleHandlerFactory-Integrated-4.0" path="*.ashx" verb="GET,HEAD,POST,DEBUG,PUT,DELETE" type="System.Web.UI.SimpleHandlerFactory" resourceType="Unspecified" requireAccess="Write" preCondition="integratedMode,runtimeVersionv4.0" />
      <add name="SimpleHandlerFactory-ISAPI-2.0" path="*.ashx" verb="GET,HEAD,POST,DEBUG,PUT,DELETE" modules="IsapiModule" scriptProcessor="%windir%\Microsoft.NET\Framework\v2.0.50727\aspnet_isapi.dll" resourceType="Unspecified" requireAccess="Script" preCondition="classicMode,runtimeVersionv2.0,bitness32" responseBufferLimit="0" />
      <add name="StaticFile" path="*" verb="GET,HEAD,POST,DEBUG,PUT,DELETE" modules="StaticFileModule,DefaultDocumentModule,DirectoryListingModule" resourceType="Either" requireAccess="Read" />
      <add name="Glimpse" path="glimpse.axd" verb="GET" type="Glimpse.AspNet.HttpHandler, Glimpse.AspNet" preCondition="integratedMode" />
    </handlers>
    <staticContent>
      <remove fileExtension=".woff" />
      <remove fileExtension=".svg" />
      <mimeMap fileExtension=".woff" mimeType="application/octet-stream" />
      <mimeMap fileExtension=".svg" mimeType="image/svg+xml" />
    </staticContent>
    <httpErrors errorMode="Custom" existingResponse="Replace">
      <remove statusCode="404" />
      <remove statusCode="500" />
      <error statusCode="404" path="/404.html" responseMode="ExecuteURL" />
      <error statusCode="500" path="/500.html" responseMode="ExecuteURL" />
      <error statusCode="503" path="/App_Offline.htm" responseMode="ExecuteURL" />
    </httpErrors>

    
  </system.webServer>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="log4net" publicKeyToken="1b44e1d426115821" />
        <codeBase version="1.2.10.0" href="log4netv1.2.10.0\log4net.dll" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
  <glimpse defaultRuntimePolicy="On" endpointBaseUri="~/Glimpse.axd">
    
  </glimpse>

**Comment by soledadtctvtn** [comment]
Any your consideration? @avanderhoorn  vs @nikmd23

**Comment by avanderhoorn** [comment]
For some reason I can't view this issue any more. Can you?

**Comment by nikmd23** [comment]
Neither can I...

**Comment by soledadtctvtn** [comment]
Using MiniProfiler on my MVC3 pages is ok, but it does not measure view render phase

**Comment by avanderhoorn** [comment]
My guess would be this part:
```
    <handlers accessPolicy="Read, Write, Execute, Script">
      <remove name="StaticFile" />
      <remove name="SimpleHandlerFactory-ISAPI-2.0" />
      <remove name="WebDAV" />
      <remove name="SimpleHandlerFactory-Integrated-4.0" />
      <remove name="SimpleHandlerFactory-Integrated" />
      <add name="SimpleHandlerFactory-Integrated" path="*.ashx" verb="GET,HEAD,POST,DEBUG,PUT,DELETE" type="System.Web.UI.SimpleHandlerFactory" resourceType="Unspecified" requireAccess="Write" preCondition="integratedMode" />
      <add name="SimpleHandlerFactory-Integrated-4.0" path="*.ashx" verb="GET,HEAD,POST,DEBUG,PUT,DELETE" type="System.Web.UI.SimpleHandlerFactory" resourceType="Unspecified" requireAccess="Write" preCondition="integratedMode,runtimeVersionv4.0" />
      <add name="SimpleHandlerFactory-ISAPI-2.0" path="*.ashx" verb="GET,HEAD,POST,DEBUG,PUT,DELETE" modules="IsapiModule" scriptProcessor="%windir%\Microsoft.NET\Framework\v2.0.50727\aspnet_isapi.dll" resourceType="Unspecified" requireAccess="Script" preCondition="classicMode,runtimeVersionv2.0,bitness32" responseBufferLimit="0" />
      <add name="StaticFile" path="*" verb="GET,HEAD,POST,DEBUG,PUT,DELETE" modules="StaticFileModule,DefaultDocumentModule,DirectoryListingModule" resourceType="Either" requireAccess="Read" />
      <add name="Glimpse" path="glimpse.axd" verb="GET" type="Glimpse.AspNet.HttpHandler, Glimpse.AspNet" preCondition="integratedMode" />
    </handlers>
```
I'm thinking that one of these other handlers is interfering. Try adding the Glimpse registration to the top of the list.

**Comment by soledadtctvtn** [comment]
I tried but no effect. Can i send my [Glimpse.log] to you, @avanderhoorn ? (if any, please show me your mailbox)
Github not support to attach file (without image), maybe :(

**Comment by avanderhoorn** [comment]
You could try sharing a dropbox/onedrive/etc link?

**Comment by soledadtctvtn** [comment]
Hi @avanderhoorn ,

You can see my log at (https://drive.google.com/file/d/0B-6uHGle9XtSbWZJV2IyQ1RtZlE/view?usp=sharing). Furthermore, i disabled urlCompression tag in web.config, but enabled staticContent.clientCache tag, so wonder if it affect the result, is it?

**Comment by soledadtctvtn** [comment]
Have you read this, @avanderhoorn ?
(https://github.com/csainty/Glimpse.RavenDb/issues/7)
