### ISSUE TITLE
Glimpse.EF6 fails

### ISSUE THREAD

**Issue by hsavran** [Glimpse/Glimpse#881]
Glimpse.EF6 fails for https://www.nuget.org/packages/EntityFrameworkWithHierarchyId/
It looks like publickkeytoken is different

**Comment by avanderhoorn** [comment]
@hsavran Any chance that you could include some of the exception details, etc.

**Comment by hsavran** [comment]
Could not load file or assembly 'EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) 


 [FileLoadException: Could not load file or assembly 'EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)] 
 Glimpse.EF.Inspector.Core.DbConnectionFactoriesExecutionTask.Execute() +0 
 Glimpse.Core.Framework.Support.ExecutionBlockBase.Execute() +153 
 Glimpse.EF.Initialize.Start() +44 

 [InvalidOperationException: The pre-application start initialization method Start on type Glimpse.EF.Initialize threw an exception with the following error message: Could not load file or assembly 'EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040).] 
 System.Web.Compilation.BuildManager.InvokePreStartInitMethodsCore(ICollection1 methods, Func1 setHostingEnvironmentCultures) +550 
 System.Web.Compilation.BuildManager.InvokePreStartInitMethods(ICollection`1 methods) +132 
 System.Web.Compilation.BuildManager.CallPreStartInitMethods(String preStartInitListPath) +90 
 System.Web.Compilation.BuildManager.ExecutePreAppStart() +135 
 System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException) +516 

 [HttpException (0x80004005): The pre-application start initialization method Start on type Glimpse.EF.Initialize threw an exception with the following error message: Could not load file or assembly 'EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040).] 
 System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9880168 
 System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101 
 System.Web.HttpRuntime.ProcessRequestInternal(HttpWorkerRequest wr) +456

**Comment by avanderhoorn** [comment]
What version of EF6 are you using and are you able to create a sample project which replicates the issue? I'm trying to narrow in on exactly what the issue is.

**Comment by hsavran** [comment]
I am using EntityFramework.HierarchyId 6.1.2 
It is the EF 6 with the HierarchyId features.

**Comment by avanderhoorn** [comment]
Do you know if it works when you don't use HierarchyId and fails when you do?

**Comment by m1dst** [comment]
I've just come across this exact issue.

There are two nuget packages available for EF6.  One is official and the other is a slightly modified version which includes some extra support for HierarchyId.  It doesn't affect core functionality.  The only difference that you would see is the PublicKeyToken is different.

Some people are getting around this by decompiling the conflicting DLL and changing the required PublicKeyToken.

Might it be possible for you resolve this another way by perhaps posting a secondary nuget package called Glimpse.EF6HierarchyId which references EntityFrameworkWithHierarchyId instead?

**Comment by m1dst** [comment]
Tried compiling the source myself, exchanging the EF nuget for the extended on but found whilst everything compiled, I got the error "Unable to cast object of type 'Glimpse.Ado.AlternateType.GlimpseDbConnection' to type 'System.Data.SqlClient.SqlConnection'."

I've googled the issue and many have seen it but it isn't clear to me why it is happening.

Close but no cigar.

**Comment by m1dst** [comment]
Even removing the new package but leaving Glimpse.Ado caused that issue so perhaps I am now to look in that library?

**Comment by m1dst** [comment]
Wonder if it is a conflict between .net versions.  IE: My project is running 4.6.1 and the libraries are 4.5.  That is the next thing to test.
