### ISSUE TITLE
SQL Tab is disabled.

### ISSUE THREAD

**Issue by ychanikornpradit** [Glimpse/Glimpse#884]
I am using VS 2013 for an MVC 5 + EF 6 + Windows Azure project.  I installed Glimpse.MVC5 and Glimpse EF6 but I the SQL tab is not clickable.  Any advise?

**Comment by avanderhoorn** [comment]
Typically the SQL tab is disabled when there isn't any data to show. In your case if you know that SQL requests are occurring and Glimpse isn't showing them, it means that Glimpse isn't detecting them for some reason. What does your data access setup look like, is there anything out of the ordinary about it?

**Comment by ychanikornpradit** [comment]
The page definitely has data to show. The solution has a DAL project separated from the MVC presentation layer.  DAL has EF 6 context connecting to the database.  I see the error message below in the Configuration tab.

FATAL

Unable to find the requested .Net Framework Data Provider.  It may not be installed.

Metadata


res://*/Entities.EconomicIncentivesEntityDataModel.csdl|res://*/Entities.EconomicIncentivesEntityDataModel.ssdl|res://*/Entities.EconomicIncentivesEntityDataModel.msl


Provider

System.Data.SqlClient

provider connection string

"data source

initial catalog

###############

persist security info

True

user id

#######

Password

########

Multiple Active Result Sets

True

App

EntityFramework"



[cid:image001.png@01D050DE.6843A5D0]

Yutthichai (UT) Chanikornpradit
Senior Associate, Pew Technology Group  |  The Pew Charitable Trusts
901 E Street, NW  |  5th Floor |  Washington, DC 20004
p: 202.540.6623  |  e: ychanikornpradit@pewtrusts.org<mailto:ychanikornpradit@pewtrusts.org>  |  www.pewtrusts.org<http://www.pewtrusts.org/>

**Comment by avanderhoorn** [comment]
Unfortunately that still isn't enough information for me to narrow down the issue. Any chance you can turn on logging and see if there are any errors that come up - http://getglimpse.com/Docs/Configuration (at the bottom).

**Comment by ychanikornpradit** [comment]
Anthony, it appears to be working now without any configuration changes.  Perhaps, it's a newbie mistake. Thank you very much for your timely assistance and an awesome product.

**Comment by avanderhoorn** [comment]
WOW thanks for the update!

**Comment by Sampath-Lokuge** [comment]
Me too had the above issue.B'cos I do have DAL layer for the EF related stuff.So the solution is ,You have to install "Glimpse.EF6" on that folder too.Then my problem vanished.Hope this will help someone else in the future.Cheers :)
