### ISSUE TITLE
Could not load file or assembly 'Glimpse.Core, Version=1.8.6.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by marknoble** [Glimpse/Glimpse#885]
I had Glimpse working on an MVC4 site and have recently been working on upgrading it to MVC5 in a branch.

Everything looks good to go and I can build and browse the site locally... however when I deploy to my Dev environment to test I get the following error:

`System.IO.FileNotFoundException: Could not load file or assembly 'Glimpse.Core, Version=1.8.6.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.`

I spoke with another Dev on our team and he suggested removing Glimpse via the NuGet Package manager, checking the code into TFS, then re-installing it and re-deploying.  It didn't help.

I also found a similar issue in these forums that was addressed by adding an ASPX file to the site root (Checking all assemblies loaded in the current appdomain for a custom attribute of type Glimpse.Core.Extensibility.NuGetPackageAttribute - https://github.com/Glimpse/Glimpse/issues/442). This seemed to work locally and all Glimpse entries are showing green... once deployed to Dev however I cannot access the ASPX page due to the error in the title.

Any suggestions for rooting out the cause of this error?

**Comment by avanderhoorn** [comment]
My guess with the latter issue you are having is that the `web.config` isn't being cleaned up correctly when you did the uninstall. Sometimes Nuget messes this up and you need to go in and remove things manually.

As to why you are getting the issue when local to the dev environment, I'm not 100% sure. By default Glimpse has some policies in place which prevent Glimpse from being accessible remotely, but this isn't your problem. I would check to see whether the Glimpse dll is in the `\bin` folder, my guess is that it is missing for some reason - either being missed in the deploy script or maybe not being restored by nuget for some reason.
