### ISSUE TITLE
Session object is null for Metadata tab

### ISSUE THREAD

**Issue by akamud** [Glimpse/Glimpse#886]
I'm using Glimpse v1.8.6 with Glimpse.MVC5 v1.5.3.0 and I'm getting a `NullReferenceException` when I load a page that uses the Session object in HttpContext.Current.

I noticed this happens only in the Metadata tab. To confirm this, I disabled this tab and confirmed the error doesn't happen anymore.

This is the error that is shown in the Metadata tab when it is enabled:

```
System.NullReferenceException: Object reference not set to an instance of an object. at System.Extensions.ToStringCurrentCulture(Decimal obj, String format) in 
e:\BitBucket\Proj.Infraestrutura\EnumsRating\Extensions.cs:line 58 at System.Extensions.ToStringPercCurrentCulture(Decimal obj) in 
e:\BitBucket\Proj.Infraestrutura\EnumsRating\Extensions.cs:line 43 at Proj.Infraestrutura.Rating.RatingPJ.ToString() in 
e:\BitBucket\Proj.Rating\Rating\Raintgs.cs:line 235 at System.Web.Mvc.ModelMetadata.GetSimpleDisplayText() at System.Web.Mvc.CachedDataAnnotationsModelMetadata.ComputeSimpleDisplayText() at System.Web.Mvc.ModelMetadata.get_SimpleDisplayText() at Glimpse.Mvc.Tab.Metadata.ProcessMetaData(ModelMetadata metadata) at Glimpse.Mvc.Tab.Metadata.GetData(ITabContext context) at Glimpse.Core.Framework.GlimpseRuntime.ExecuteTabs(RuntimeEvent runtimeEvent)
```
This is the code that throws an error, it is called by one of the members that gets rendered in the page, so I'm assuming Glimpse tries to "ToString" it but gets a null object for Session.

```C#
public static string ToStringCurrentCulture(this decimal obj, string format = null)
{
    return obj.ToString(format ?? "N2", (HttpContext.Current.Session["culture"] != null ? (CultureInfo)HttpContext.Current.Session["culture"] : new CultureInfo("pt-BR")));
}
```

I tried searching for a similar issue, I only found a problem with the Session object when using a CustomRuntimePolicy, but I am running the default policy, like this:
```XML
<glimpse defaultRuntimePolicy="On" endpointBaseUri="~/Glimpse.axd" />
```
Is this expected? Shouldn't Glimpse only run when the session object is initialized?

Here is the log when that error occurs: [Gist](https://gist.github.com/akamud/43719b6af69619d86f63)

**Comment by CGijbels** [comment]
The reason why you get this `NullReferenceException` is that there is _timing_ mismatch between your code and the Glimpse runtime events.

In this case, the `Metadata` Tab is being executed at `RuntimeEvent.EndRequest` which is executed by Glimpse in an ASP.NET environment when the `PostReleaseRequestState` event is raised on the `HttpApplication` instance processing the request. Now the thing is that that event is raised __after__ the `PostRequestHandlerExecute` after which the session is closed.

The question here is why does a `ToString()` rely on the Session? This might give you problems at different moments as well, no?

Either way, if we look at your `ToStringCurrentCulture` method, then this can be solved quite easily as well, by checking the `Session` property for `null` before trying to get the culture value out of it, because if there is no culture value, then you already have a fall back to a default culture, so why not have the same fallback when the `Session` is not available?

```
public static string ToStringCurrentCulture(this decimal obj, string format = null)
{
    return obj.ToString(format ?? "N2", (HttpContext.Current.Session != null && HttpContext.Current.Session["culture"] != null ? (CultureInfo)HttpContext.Current.Session["culture"] : new CultureInfo("pt-BR")));
}
```

I would also suggest to store the culture value as you are requesting the culture value twice from the `Session` object. Also the default culture could be a static readonly field, so that it doesn't need to be instantiated every time there is no `Session` or no culture in the `Session`

```
private static readonly CultureInfo _defaultCultureInfo = new CultureInfo("pt-BR");
public static string ToStringCurrentCulture(this decimal obj, string format = null)
{
     var cultureInfo = (HttpContext.Current.Session != null ? HttpContext.Current.Session["culture"] as CultureInfo : null) ?? _defaultCultureInfo;
     return obj.ToString(format ?? "N2", cultureInfo);
}
```

**Comment by akamud** [comment]
Thanks a lot for the tips @CGijbels, I will do the improvements you suggested.

If for some reason I really needed the session, how could I make Glimpse run before it is closed? Is there a way?

**Comment by CGijbels** [comment]
Well you could just inherit from the `Glimpse.Mvc.Tab.Metadata` tab and modify the `RuntimeEvent` on which the `GlimpseRuntime` should ask for its data

```
public class MyMetadataTab : Glimpse.Mvc.Tab.Metadata
{
    public override RuntimeEvent ExecuteOn
    {
        get { return RuntimeEvent.EndSessionAccess; }
    }
}
```

and make sure you configure Glimpse to ignore the original one, but adapting the web.config like so:

``` xml
<glimpse defaultRuntimePolicy="On" endpointBaseUri="~/Glimpse.axd">
    ...
    <tabs>
        <ignoredTypes>
            <add type="Glimpse.Mvc.Tab.Metadata, Glimpse.Mvc" />
        </ignoredTypes>
    </tabs>
</glimpse>
```

Give that a try I would say (maybe even before the other suggested changes, making sure you would still get the original exception in case `Session` is not available)

**Comment by akamud** [comment]
Thanks @CGijbels, that did the trick! No problems using the session object this way.

I think this would be a good solution for anyone trying to use the session object for some reason.

**Comment by avanderhoorn** [comment]
Humm wonder if its worth adding this workaround to the docs? @akamud would you like to add it to [this](https://github.com/Glimpse/Glimpse/wiki/Troubleshooting) page?

**Comment by akamud** [comment]
I think so. I saw a question on StackOverflow that was similar to this, but didn't show the workaround for existing tabs, like @CGijbels showed.

I would gladly add this to the documentation.

**Comment by akamud** [comment]
I added this information to the page you linked, @avanderhoorn, tell me if I can improve it or if I said something wrong.

When I started searching for a solution I missed [RuntimeEvent](https://github.com/Glimpse/Glimpse/blob/master/source/Glimpse.Core/Extensibility/RuntimeEvent.cs) documentation being more accessible, in fact, I just realized this was a possibility after @CGijbels said so. I think this would be a valuable information in the [Custom Tabs](https://github.com/Glimpse/Glimpse/wiki/Custom-Tabs) page, what do you think?

**Comment by avanderhoorn** [comment]
@akamud go for it! Just add it in were you think it should go. I think it will be a great addition.
