### ISSUE TITLE
Update on progress for v2?

### ISSUE THREAD

**Issue by ravensorb** [Glimpse/Glimpse#890]
Any plans or ETA for v2?

**Comment by avanderhoorn** [comment]
@ravensorb To track current progress, you can have a look at - https://github.com/avanderhoorn/Glimpse.Prototype/ & the issues list. We started on v2 a while back but with the advent of AspNet vNext and .Net Core, that through a spanner in the works and we had to reassess the approach taken.

Given that we are tracking with AspNet vNext and .Net Core, we have been spending a fair amount of time making sure that we can get the information out we need. That has meant we have spent time working on that code base and providing feedback. 

In terms of exact dates, thats hard to pin down at the moment with the way AspNet vNext and .Net Core is evolving at the moment, but if anyone wants to get involved, feel free to look at the issues list on the prototype repo and reach out.

**Comment by glen-84** [comment]
@avanderhoorn,

Do you have any idea when you might be able to release an alpha version, with some basic request timing info and maybe EF7 logging?

**Comment by avanderhoorn** [comment]
Unfortunately thats kind of hard to predict as we are waiting on bits and pieces from the aspnet team to continue moving forward in particular area. In the mean time, I'm putting out a release for v1 this week (assuming a PR is finished up that we are waiting on) and we plan to keep accepting and working on items there till v2 comes out.

**Comment by glen-84** [comment]
Sure, I understand.

I can't use v1 though, since I'm working with ASP.NET 5.

**Comment by avanderhoorn** [comment]
@glen-84 Which is your blocking issue?

**Comment by glen-84** [comment]
I'm not sure what you mean. v1 doesn't work with ASP.NET 5, right?

**Comment by avanderhoorn** [comment]
Oh I see. Yes Glimpse v1 does not and will not be enhanced to work with
asp.net 5. That's what v2 is all about. Sorry about causing confusion.

**Comment by avanderhoorn** [comment]
See https://github.com/Glimpse/Glimpse.Prototype/ for more updates
