### ISSUE TITLE
Error: 'glimpse' is undefined

### ISSUE THREAD

**Issue by KevinBurton** [Glimpse/Glimpse#891]
I recently installed Glimpse to a project that already had ELMAH installed now when I go to /elmah.axd I get 

Line: 1
Error: 'glimpse' is undefined

Ideas?
![glimpse](https://cloud.githubusercontent.com/assets/2643566/6844999/e3cd0f08-d37d-11e4-9517-233ecc3485a4.jpg)

**Comment by avanderhoorn** [comment]
Do you get this error within Visual Studio or when you run your site in the browser? Also, did this error come up when you installed the package or when you ran your site.

**Comment by RehanSaeed** [comment]
This error seems related to mine https://github.com/Glimpse/Glimpse/issues/887.
