### ISSUE TITLE
Glimpse not working on MVC4

### ISSUE THREAD

**Issue by Mirodil** [Glimpse/Glimpse#893]
"Glimpse" icons appear but appears only the following:
No data has been found. This could be caused because:

- the data is still loading by the client, or
- no data has been received from the server (check to see if the data & metadata payloads are present), or
- no plugin has been loaded, or
- an error has been thrown in the client (please check your JavaScript console and let us know if anything is up).

**Comment by avanderhoorn** [comment]
Have you had a look at the following - http://getglimpse.com/Docs/Troubleshooting. Failing that, are you able to turn on logging to see what the issue might be.
