### ISSUE TITLE
suppress versionCheck

### ISSUE THREAD

**Issue by ariovistus** [Glimpse/Glimpse#895]
is there a way to prevent the versionCheck ajax call from happening without e.g. making a custom build of glimpse?

**Comment by avanderhoorn** [comment]
Currently there is no way to do this. We never thought anyone would be interested in not knowing about updates. That said, if you are interested in doing the work, it shouldn't be that hard to put in and I can give you some pointers on where to start.

**Comment by ariovistus** [comment]
Well, it's not so much about not knowing about updates as it is not appropriate to be making gratuitous network calls in a production environment. I could probably do the work when I get some time.

**Comment by avanderhoorn** [comment]
Sounds like a plan.

**Comment by ariovistus** [comment]
Looks like the check happens in javascript and can be short circuited here: https://github.com/Glimpse/Glimpse/blob/61857be49fdab5af887d70cc9d85ff4a4a3a7358/source/Glimpse.Core/glimpse.js#L2129 

A global variable would git 'er done, but wouldn't go too far towards ensuring no page in your webapp does the check. Would it make sense to add a policy to glimpse and inject a bit of javascript if the policy says it's appropriate?
