### ISSUE TITLE
How do I "enabled in a read only capacity"?

### ISSUE THREAD

**Issue by NotMyself** [Glimpse/Glimpse#900]
I want to be able to view user sessions for debugging purposes. I am attempting to follow the setup instructions for the History tab located [here](https://github.com/Glimpse/Glimpse/wiki/History-Tab#setup). I am not clear how I enable glimpse in a read only capacity, and my google-fu is failing me. Can someone point me in the right direction?

**Comment by CGijbels** [comment]
Hi @NotMyself , I answered your SO question so that I might be easier to find for others searching for similar things. I hope it is what you were asking for

**Comment by NotMyself** [comment]
@CGijbels exactly what I was looking for, thanks. I added your response to the wiki page that caused the confusion for me. Hopefully it will help others.
