### ISSUE TITLE
Got 404 not found page for local custom host name

### ISSUE THREAD

**Issue by conggit** [Glimpse/Glimpse#906]
Hi guys,

After installing Glimpse for MVC 5 and EF6, I got 404 resource not found page when navigating to ~/glimpse.axd when I use local custom host name. For example, the request URL is: http://v.foo.com/glimpse.axd, where "v.foo.com" is my local custom host name. I've added the following section inside runtimePolicies in web.config, but still no luck. Please help.

```
<ignoredTypes>
        <add type="Glimpse.AspNet.Policy.LocalPolicy, Glimpse.AspNet"/>
        <add type="Glimpse.Core.Policy.ControlCookiePolicy, Glimpse.Core"/>
</ignoredTypes>
```

**Comment by avanderhoorn** [comment]
That's weird as I've never heard of anyone having similar issues. If you don't use the local custom host name and just use "localhost" do you have the same issue?

**Comment by conggit** [comment]
"localhost" is no prob. The problem is just for local custom host name... Does anyone know how to fix this or this is a bug of Glimpse?
