### ISSUE TITLE
Glimpse hides behind some parts of page

### ISSUE THREAD

**Issue by mesuttalebi** [Glimpse/Glimpse#907]
Glimpse some times hidden behind of another tag is page.
![1](https://cloud.githubusercontent.com/assets/3634757/7981434/7f2d7260-0ab7-11e5-8846-a9ff40cd910d.png)

please add a z-index with very large number so, glimpse shown in front of every thing in the page like below:

![2](https://cloud.githubusercontent.com/assets/3634757/7981513/26b9ba98-0ab8-11e5-982c-5ba6beef9407.png)

**Comment by dainovec** [comment]
experiencing same issue, workaround is to add
    
    .glimpse * {
        z-index: 9999;
    }

into css, however it would be nicer if generated style would include this rule.
