### ISSUE TITLE
X-Forwarded-Proto

### ISSUE THREAD

**Issue by nemaroller** [Glimpse/Glimpse#912]
For a SSL request, Glimpse accurately injects a https request to its injection script.

However, if a load balancer terminates a SSL request, thereby having the local IIS receive a normal HTTP request, there is no manner in which to force Glimpse to request its injection script via https. Consequently, it's injection script fails from the client browser due to it being request in an insecure manner.

There should be either one of two mechanisms:
1) Inspect for X-Forwarded-Proto which many clouds use to indicate a terminated SSL request.
2) Add a setting to the Glimpse configuration to force HTTPs request for the injection script.

**Comment by avanderhoorn** [comment]
Shifted this to the task list. Will track from there.
