### ISSUE TITLE
Date parameters are not quoted in SQL inspector

### ISSUE THREAD

**Issue by mstijak** [Glimpse/Glimpse#913]
Glimpse does a great job inserting parameter values into the query, however date parameters are not quoted which requires fixing the SQL after copying it.

![example](https://cloud.githubusercontent.com/assets/433394/8226333/1d0a7c1c-159e-11e5-82f7-ee9b96e85db9.png)

**Comment by iliakolesnikov** [comment]
Also it will be cool to make date format configurable (i need ISO 8601).
