### ISSUE TITLE
Already referencing a newer version of 'EntityFramework.de

### ISSUE THREAD

**Issue by Otto404** [Glimpse/Glimpse#915]
PM> install-package glimpse.mvc5
Attempting to gather dependencies information for package 'glimpse.mvc5.1.5.3' with respect to project targeting '.NETFramework, Version=v4.6'
Attempting to resolve dependencies for package 'glimpse.mvc5.1.5.3' with DependencyBehavior 'Lowest'
Resolving actions to install package 'glimpse.mvc5.1.5.3'
install-package : Already referencing a newer version of 'EntityFramework.de'..
In Zeile:1 Zeichen:1
+ install-package glimpse.mvc5
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by avanderhoorn** [comment]
No idea what this error means. Is it preventing the packages being
installed? Also are you able to replicate the problem with a blank project?

**Comment by Otto404** [comment]
Yes, this error prevents the packaged being installed. after the re-installation of entity-framework the Installation of glimpse worked without error.
