### ISSUE TITLE
Glimpse.WebForms - Server.Execute causes an exception around viewstate

### ISSUE THREAD

**Issue by subshock** [Glimpse/Glimpse#917]
When Glimpse is active, if a page uses Server.Execute then an exception is raised when the page is being rendered.  It looks like viewstate registered by Glimpse in the inner page is interfering with that registered in the outer page.

The exception message and stacktrace:
[ArgumentException: Item has already been added. Key in dictionary: '_GlimpseWebFormViewState'  Key being added: '_GlimpseWebFormViewState']
   System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add) +10930454
   System.Collections.Hashtable.Add(Object key, Object value) +10
   Glimpse.WebForms.Inspector.ViewStatePageStatePersister.Save() +357
   System.Web.UI.Page.SavePageStateToPersistenceMedium(Object state) +108
   System.Web.UI.Page.SaveAllState() +659
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +1225

**Comment by eithe** [comment]
I'm also seeing this when using routes in an web forms asp.net 4.5 website. If I go to pages with the direct urls everything works, but if I use the route url this error is thrown.

**Comment by avanderhoorn** [comment]
Any thoughts on a possible fix/workaround?

**Comment by eithe** [comment]
Unfortunately I need to move on now, it worked on the two pages I needed to debug, and I was able to solve the issue I had. I then uninstalled Glimpse again (since most of my pages failed), will take another look the next time I need to use Glimpse.

**Comment by guushamann** [comment]
I get this error as well.

wat we do is this:

1. create a webform page with a button for htmltopdf
2. Server.Execute the same webform to get its html for pdf generating

on 2. Server.Execute i get the same viewstate error

**Comment by guushamann** [comment]
I did a pull request with the fix for this error

https://github.com/Glimpse/Glimpse/pull/951
