### ISSUE TITLE
Web Api Help

### ISSUE THREAD

**Issue by rsantosdev** [Glimpse/Glimpse#919]
Hi guys,

My scenario is that I use an mvc project that serves an initial page and I do work with angular calling an webApi project. I need to add glimpse on the webapi project.

I managed to do what is described here: http://stackoverflow.com/questions/23911061/using-glimpse-on-a-javascript-website

But my history tab does not show any call to my api. just the call I made to the index page that loads the glimpse plugin.

Is there any way to work with glimpse on web api? I saw a pull request where people is working but I couldnt understand how install that on mine.

Thanks in advance for any help

**Comment by avanderhoorn** [comment]
Unfortunately we don't support WebAPI atm. That said, the progress is being tracked at #226
