### ISSUE TITLE
Add an alternate set of strong name signed glimpse packages to nuget

### ISSUE THREAD

**Issue by ryandle** [Glimpse/Glimpse#920]
The only glimpse packages currently available in nugget are not strong name signed. If someone requires strong name signed assemblies in their project, I believe their options are:

1. Get a copy of the source and rebuild the desired packages with strong name signing
2. Download the desired glimpse packages from nuget and use a tool like [Brutal Strong Name Signer](http://www.nuget.org/packages/Brutal.Dev.StrongNameSigner/) to sign the assemblies.

Neither option is great. Both are time consuming and have to be repeated for any new version of glimpse.

The ask here is to generate both signed & unsigned assemblies and host both on nuget.

From what I can tell, Glimpse currently depends on the following packages which do not have strong names:
* Antlr4.StringTemplate
* Tavis.UriTemplates

We'd likely need versions of these dependencies with strong name signatures in order to compile Glimpse.Core.

Alternatively, perhaps the signing can be pushed to the ilmerge stage for Glimpse.Core which might remove the need for its dependencies to be strong name signed? I'm not 100% sure about this alternative.

Btw, the StackExchange.Redis package is an example of a project that does this:
* http://www.nuget.org/packages/StackExchange.Redis/
* http://www.nuget.org/packages/StackExchange.Redis.StrongName

**Comment by populov** [comment]
I'd wish to have signed Glimpse too, but project owners have different point of view: #324, #879

**Comment by nikmd23** [comment]
Hi @ryandle,

As [I've mentioned in the past](https://github.com/Glimpse/Glimpse/issues/879#issuecomment-73115674), I don't have a problem shipping `*.StrongName` packages to [MyGet](http://myget.org/). I don't think the update to our [`default.ps1`](https://github.com/Glimpse/Glimpse/blob/master/default.ps1) script would be *that* difficult. 

Would you like to update it, and we can take your PR?

**Comment by populov** [comment]
@nikmd23, the problem is not only Glimpse itself, but I also have to recompile from sources every plugin that I use, because packaged plugin versions depend on unsigned Glimpse.Core.dll. Packages work well until I want to write some extension, like custom security policy - so I need signed Glimpse for my code and unsigned for plugins, or recompile pligins.

Maybe I missed something, but could you point out changes, that solves signing problem anyhow?

I don't want to seem unthankfull, Glimpse is great, I love it, but multiple projects resignig an recompiling is a piece of pain.

**Comment by ryandle** [comment]
@nikmd23 sigh, sorry, I thought I searched for related issues before opening this one but I clearly did not.

The MyGet proposal works for me and I'll try to take a stab at it.

Out of curiosity, why not put it on nuget.org? From reading the previous discussions on this topic, it looks like the primary concern is glimpse extensions taking a dependency on the strong named version (and the headaches that would come with that.) Is hosting it on MyGet a way to discourage this behavior, or is there more to it that I'm missing?

**Comment by nikmd23** [comment]
@ryandle, yes, the idea behind hosting it on NuGet is to discourage this becoming the default behavior, while still offering a (partial?) solution for people in your shoes.
