### ISSUE TITLE
Glimpse standalone with XML

### ISSUE THREAD

**Issue by akamud** [Glimpse/Glimpse#922]
I just noticed that when running a Web Api project that returns XML, Glimpse standalone doesn't work. If I change my formatter to JSON, it works fine and my requests get logged.  
I feel it has a good explanation based on Glimpse functionality, but it might be a bug.

So, is this a bug or am I missing something?

**Comment by avanderhoorn** [comment]
Unfortunately there isn't much I can do at the moment. That said, the progress is being tracked at #226
