### ISSUE TITLE
Glimpse standalone doesn't work when Web Api is registered on Startup class

### ISSUE THREAD

**Issue by akamud** [Glimpse/Glimpse#924]
I have a Web Api 2 (5.2.3) project using Owin and I am trying to use Glimpse standalone mode, I don't have MVC on the project (I did an empty project with Web Api added), so the only way to open Glimpse is using the popup window.

When I try to open Glimpse I always get the "**Sorry no requests are currently available**" message. After some investigation the culprit seems to be using only the `Startup` class to configure WebApi. Originally my `Global.asax.cs` is empty.  

This is my Startup.cs:
```C#
public class Startup
{
	public void Configuration(IAppBuilder app)
	{
		HttpConfiguration config = new HttpConfiguration();
		WebApiConfig.Register(config);

		app.UseWebApi(config);
	}
}
```

I did a test where I just added this in my `Global.asax` and it started working:
```C#
protected void Application_Start(object sender, EventArgs e)
{
    // Remove this and Glimpse stops working again
    GlobalConfiguration.Configure(WebApiConfig.Register);
}
```

Although I'm doing all my configuration in `Startup.cs`, I'm not using OWIN self-hosted, I'm using IIS.

I created a minimal sample project where you can see this behavior consistently when you comment the `Global.asax` code. The only thing I did different from the starting template was removing the XML formatter and adding the `Startup` class. You can see the sample [here](https://github.com/akamud/GlimpseSample).

Nugets used:
```XML
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Glimpse" version="1.8.6" targetFramework="net452" />
  <package id="Glimpse.AspNet" version="1.9.2" targetFramework="net452" />
  <package id="Glimpse.Mvc5" version="1.5.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.Owin" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="1.0.0" targetFramework="net452" />
  <package id="Microsoft.Net.Compilers" version="1.0.0" targetFramework="net452" developmentDependency="true" />
  <package id="Microsoft.Owin" version="3.0.1" targetFramework="net452" />
  <package id="Newtonsoft.Json" version="6.0.4" targetFramework="net452" />
  <package id="Owin" version="1.0" targetFramework="net452" />
</packages>
```

So, my question is: how can I make Glimpse work in a scenario like that, where all my configuration are in the `Startup` class and I have no `Global.asax`?

**Comment by gmanolache** [comment]
I'm having the same issue

**Comment by ernestopye** [comment]
+1

**Comment by JustMaier** [comment]
+1

I think there is a [known issue with Glimpse and OWIN](https://github.com/Glimpse/Glimpse/issues/739) and it won't be fixed until v2... Which is for ASP.Net 5 only ATM
