### ISSUE TITLE
Black rhomb with a question mark instead of the russian letter

### ISSUE THREAD

**Issue by zodchiy** [Glimpse/Glimpse#926]
I turned on the Glimpse, and I got this result in datatable on page from db - "Тульская о��ласть", instead of "Тульская область".
After turned off the Glimpse, this effect disappeared.

Codepage of all pages is UTF-8 with signature. DB codepage is SQL_Latin1_General_CP1251_CI_AS.
This result occurs only when the Glimpse is turned on.

**Comment by avanderhoorn** [comment]
Unfortunately there isn't much I can do at the moment. That said, the progress is being tracked at #226
