### ISSUE TITLE
Application hangs at UserManager.FindByNameAsync when using Glimpse.EF6 (v1.6.5)

### ISSUE THREAD

**Issue by encounter12** [Glimpse/Glimpse#928]
Application hangs at UserManager.FindByNameAsync when using Glimpse.EF6 (v1.6.5)

Issue: When trying to get a single student details from Web Application <a href="https://github.com/encounter12/School.Me" target="_blank">School.Me</a> the application hangs at: ApplicationUser user = userManager.FindByNameAsync(username).Result (see: <a href="https://github.com/encounter12/School.Me/blob/master/School/School.Data/Repositories/StudentRepository.cs#L22" target="_blank">StudentRepository.cs, line 22</a>) and a circle keeps spinning in the browser. The problem started after installing Glimpse.EF6 (v1.6.5) which also installs as a dependency Glimpse.Ado v1.7.3. After uninstalling Glimpse.EF6 and Glimpse.Ado, the issue gets resolved.

P.S. Please have in mind that the latest changes (installing Glimpse.EF6) have not been committed to my GitHub project.
Related packages:

..NET Framework v4.5
IIS Express v10.0.1734

Microsoft.AspNet.Mvc v5.2.3
Microsoft.AspNet.Identity.Core v2.2.0
Microsoft.AspNet.Identity.EntityFramework v2.2.0
Microsoft.AspNet.Identity.Owin v2.2.0
EntityFramework v6.1.3

The same problem appears after updating some packages to:

Microsoft.AspNet.Identity.Core v2.2.1
Microsoft.AspNet.Identity.EntityFramework v2.2.1
Microsoft.AspNet.Identity.Owin v2.2.1

Installed Glimpse Packages:

Glimpse v1.8.6
Glimpse.AspNet v1.9.2
Glimpse.Mvc5 v1.5.3
Glimpse.EF6 v1.6.5
Glimpse.Ado v1.7.3

**Comment by SergeyKanzhelev** [comment]
By hang - do you mean that it hang in C# code or that circle keep spinning? If first - what is the callstack of the hang? If second - there is a bug in the framework 4.5 that was addressed in FW 4.6. In certain combination of async calls, stream flushes and using of ```PreSendRequestHeaders``` callback you may get request processing pipeline corrupted. So if it is second - can you try to upgrade to framework 4.6?

**Comment by encounter12** [comment]
When I run the application in Debug mode it reaches to the method <a href="https://github.com/encounter12/School.Me/blob/master/School/School.Data/Repositories/StudentRepository.cs#L22" target="_blank">UserManager.FindByNameAsync</a> and then redirects me back to the browser and the browser circle keeps spinning indefinitely. In Visual Studio 2015 nothing appears under Call Stack at that point. I already have .NET Framework 4.6 installed, so I have followed your advice and set the target framework to all projects in the VS Solution to 4.6, but the problem was not solved. After uninstalling Glimpse.EF6 (v1.6.5) and Glimpse.Ado (v1.7.3) the problem gets resolved again. So, I consider this issue to be Glimpse.EF6 / Glimpse.Ado related instead of .NET Framework / Microsoft.AspNet.Identitiy.Core 2.2.1 related.

P.S. While having Glimpse.EF6 and Glimpse.Ado installed I emptied the contents of Glimpse.log file and tried to open: ~/Administration/Students/Details/student0002 but nothing gets recorded. Here it is the content of Glimpse.log file (after removing Glimpse.EF6 and Glimpse.Ado) when I open the above route:

2015-09-08 11:31:48.8581 | INFO | Replaced IView of type 'System.Web.Mvc.RazorView', named 'Details', with proxy implementation. | 
2015-09-08 11:31:48.9411 | INFO | Replaced IView of type 'System.Web.Mvc.RazorView', named '_LoginPartial', with proxy implementation. | 
2015-09-08 11:31:49.0261 | DEBUG | RuntimePolicy set to 'ExecuteResourceOnly' by IRuntimePolicy of type 'Glimpse.Core.Policy.GlimpseResourcePolicy' during RuntimeEvent 'ExecuteResource'. | 
2015-09-08 11:31:49.0451 | DEBUG | RuntimePolicy set to 'Off' by IRuntimePolicy of type 'Glimpse.Core.Policy.ContentTypePolicy' during RuntimeEvent 'EndRequest'. | 
2015-09-08 11:31:49.5512 | DEBUG | RuntimePolicy set to 'ModifyResponseHeaders' by IRuntimePolicy of type 'Glimpse.Core.Policy.AjaxPolicy' during RuntimeEvent 'BeginRequest'. | 
2015-09-08 11:31:49.5512 | DEBUG | RuntimePolicy set to 'Off' by IRuntimePolicy of type 'Glimpse.Core.Policy.UriPolicy' during RuntimeEvent 'BeginRequest'. |

**Comment by encounter12** [comment]
One more note. Having Glimpse.EF6 v1.6.5 and Glimpse.Ado v1.7.3 installed when I replace the async method FindByNameAsync with its non-async counterpart FindByName everything works fine.

Replacing the line:

ApplicationUser user = userManager.FindByNameAsync(username).Result;

with:

ApplicationUser user = userManager.FindByName(username);

**Comment by VahidN** [comment]
@encounter12
`Result` is a blocking property and it will cause a deadlock.
[More info here](http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html)

**Comment by encounter12** [comment]
@VahidN
Thank you very much for your assistance and the provided link! It seems that I was mixing synchronous with asynchronous code. Now I have changed the line of code from:

```csharp
ApplicationUser user = userManager.FindByNameAsync(username).Result;
```
to: 

```csharp
ApplicationUser user = await userManager.FindByNameAsync(username);
```
and refactored all its parent methods to be asynchronous (```async Task<Type>```) including the Action method in the controller:

```csharp
public async Task<ActionResult> Details(string username)
{
   	// code omitted for clarity

    Student student = await this.studentService.GetByUserName(username);

    // code omitted for clarity

    return View(model);
}
```

 Now everything is working fine and there is no deadlock. I am closing this issue. Thanks again!
