### ISSUE TITLE
Invalid operation. The connection is closed Glimpse Error

### ISSUE THREAD

**Issue by jatinkhimani** [Glimpse/Glimpse#930]
Hi Guys,

I get this glimpse error while i run my third party control.

Property accessor 'ServerVersion' on object 'Glimpse.Ado.AlternateType.GlimpseDbConnection' threw the following exception:'Invalid operation. The connection is closed.'

![image](https://cloud.githubusercontent.com/assets/11959865/9933439/84e47ccc-5d68-11e5-882d-78d2a9ea3fec.png)

I get perfect data from repository but when DOM is try to bind it at that time it's throw error.
Do you have any idea about it how can i resolve it ? 

FYI : i use Component one flexgrid for biding data.

Thanks,
Jatin

**Comment by avanderhoorn** [comment]
I'm assuming things work if you don't use Glimpse?

**Comment by jatinkhimani** [comment]
No it's also not work without glimpse. 
but we are confuse about the issue.

Is there anything that i need to take care externally for Glimpse ?
or Is there any Sqlconnection dependency for Glimpse connection ?
