### ISSUE TITLE
Glimpse SQL tab substitutes null parameters with 'NULL' instead of NULL

### ISSUE THREAD

**Issue by burnchar** [Glimpse/Glimpse#933]
The Glimpse SQL tab is incredibly useful in that the displayed SQL text replaces parameter names with the value of that parameter.
However, when the parameter's value is NULL, Glimpse replaces it with the string 'NULL', which has a totally different meaning.
Glimpse displays the following, which searches `SomeTextField` for test that literally begins with the characters NULL:
```sql
SELECT * FROM T
WHERE ('NULL' /* @search */ IS NULL OR SomeTextField LIKE 'NULL' /* @search */ + '%'
```

Correct SQL is the following (no quotes around NULL) which searches for text beginning with the parameter value (or in the case of NULL, skips the search altogether)
```sql
SELECT * FROM T
WHERE (NULL /* @search */ IS NULL OR SomeTextField LIKE NULL /* @search */ + '%'
```

This is subtle and may cause problems for developers that try to execute the Glimpse SQL text because it will return different results than the actual SQL with parameters bound to NULL.

**Comment by avanderhoorn** [comment]
Unfortunately there isn't much I can do at the moment. That said, the progress is being tracked at #226
