### ISSUE TITLE
Glimpse does not permit open connection with azure tables

### ISSUE THREAD

**Issue by Compuanalisis** [Glimpse/Glimpse#934]
When I installed glimpse for MVC5 project I can not save info into azure tables, because does not permit to execute this line of code "  CloudStorageAccount maccount = CloudStorageAccount.Parse(CloudConfigurationManager.GetSetting("cxxxxxxxx"));".

**Comment by avanderhoorn** [comment]
Unfortunately there isn't much I can do at the moment. That said, the progress is being tracked at #226
