### ISSUE TITLE
Issue with Glimpse Standalone mode

### ISSUE THREAD

**Issue by tsramanathan** [Glimpse/Glimpse#937]
Hello Glimpse Team,

I enabled glimpse to troubleshoot an WebAPI project.  When I try to Launch the standalone mode it is throwing me the following.  Could you please help me address this issue?

{
Sorry no requests are currently available

This is a current limitation of this feature. For Glimpse client to work, Glimpse has to detect at least one requesting for which it is enabled.

If you are using this feature and it is causing you issues, please let us know
}

Thanks

Ram

**Comment by avanderhoorn** [comment]
Unfortunately there isn't much I can do at the moment. That said, the progress is being tracked at #226
