### ISSUE TITLE
Glimpse issue, or VS Code or RC1?

### ISSUE THREAD

**Issue by spboyer** [Glimpse/Glimpse#939]
@avanderhoorn 

Everything is working great, however getting unresolved issues in the editor.

VS Code 0.10.1 on Yosemite OS X

![screen shot 2015-11-20 at 6 37 58 am](https://cloud.githubusercontent.com/assets/7681382/11299070/9bcbe81a-8f51-11e5-9984-68ddc6992fcb.png)
![screen shot 2015-11-20 at 6 37 38 am](https://cloud.githubusercontent.com/assets/7681382/11299074/a24b7b9c-8f51-11e5-8b54-b4415d9bcad3.png)

@chrisdias

**Comment by avanderhoorn** [comment]
Does glimpse still run or does this exception stop the app from running?

**Comment by spboyer** [comment]
Still runs. Code on http://github.com/spboyer/cleanshave

**Comment by nikmd23** [comment]
Hey Shane! Good to hear from you.

Certainly weird given that the code does in fact compile and work. To be honest, I've seen this in Visual Studio w/ Resharper from time to time to - but with other methods/types, not just Glimpse.

Safe to assume you're getting all these packages directly from NuGet.org's feed (not a MyGet feed) and on `1.0.0-rc1-final` build of dnx?

**Comment by spboyer** [comment]
@nikmd23 - pretty safe here is the info:

NuGet.config
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="AspNetVNext" value="https://www.myget.org/F/aspnetvnext/api/v2/" />
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </packageSources>
  <disabledPackageSources />
</configuration>
```
and dnvm list
```
Active Version              Runtime Architecture OperatingSystem Alias
------ -------              ------- ------------ --------------- -----
       1.0.0-beta7          coreclr x64          darwin
  *    1.0.0-rc1-final      coreclr x64          darwin          default
       1.0.0-rc1-final      mono                 linux/osx
```

**Comment by spboyer** [comment]
@nikmd23 let me remove the myget.org entry and see if that helps...

**Comment by avanderhoorn** [comment]
I've had this happen a couple of times but in full VS. The app would still run and glimpse would still work but full VS would bring up the exact same message you posted for VS Code. Hence I'm wondering if its a bug in Roslyn???

**Comment by spboyer** [comment]
Weird it happens on one machine and not another, feasibly setup the same way.

Did verify that the package does in fact only come from `https://www.nuget.org/api/v2/FindPackagesById()?id='Glimpse'` @nikmd23

**Comment by spboyer** [comment]
@nikmd23 @avanderhoorn - Maybe this is an Omnisharp issue. I opened in Atom here is the full dump from the output on startup in a gist

https://gist.github.com/spboyer/67fc7c8669ddd8cb6448

**Comment by spboyer** [comment]
Confirmed. When I remove the "Glimpse" package from project.json the Omnisharp server starts fine.  When it is there is ERRORS in VSCode, seems to recover ok in ATOM but the above issue is still there.

**Comment by avanderhoorn** [comment]
No idea why it would have any problem with what we are doing. Its not like we are doing anything funky...

**Comment by nikmd23** [comment]
I wonder if @david-driscoll has any insight into this?

**Comment by david-driscoll** [comment]
Very strange, it's like OmniSharp isn't seeing that package is compatible with `aspnet50`, is the repo public? Maybe make an issue on the omnisharp-roslyn repo.  I hope to have some time this week or weekend.

**Comment by avanderhoorn** [comment]
Yep repo is public... code/project.json's in question are here https://github.com/Glimpse/Glimpse.Prototype

**Comment by avanderhoorn** [comment]
Further issues should be raised at Glimpse/Glimpse.Prototype
