### ISSUE TITLE
How to disable glimpse update check request?

### ISSUE THREAD

**Issue by oguzhantopcu** [Glimpse/Glimpse#941]
I have noticed that glimpse checks for any update on clientside via https://getglimpse.com/Api/Version/Check?Glimpse.Ado=1.7.3&Glimpse.AspNet=1.9.2&Glimpse=1.8.6&Glimpse.EF6=1.6.5&Glimpse.Mvc5=1.5.3&stamp=1450129430335&callback=glimpse.versionCheck.result . Can I disable this?

http://prntscr.com/9edgdy

Also request couldnt be completed since link's certificate is not valid.

How can I disable it?

**Comment by avanderhoorn** [comment]
Unfortunately there isn't much I can do at the moment. That said, the progress is being tracked at #226
