### ISSUE TITLE
Conflict with RazorEngine

### ISSUE THREAD

**Issue by neuoy** [Glimpse/Glimpse#942]
Hi,

I have an issue with Glimpse 1.8.6 and RazorEngine 3.6.4 (both installed from NuGet, RazorEngine is only referenced from a separate assembly if that matters).

When RazorEngine compiles a view, I get the following exception: System.NotSupportedException
`Some environments conflict with current Glimpse async support. Please set Glimpse:DisableAsyncSupport = true in Web.config, or see https://github.com/Glimpse/Glimpse/issues/632 for more details.`

I've looked at issues #632 and #896 but
- the workaround proposed here doesn't work: https://github.com/Glimpse/Glimpse/issues/632#issuecomment-29020863 (there is no key "Glimpse.HttpContext" in the CallContext but I still get the exception, setting HttpContext.Current to null doesn't help either ; actually, when the view is compiled, I'm not processing a web request at all, which is why I needed RazorEngine in the first place)
- it's not clear for me if disabling async support will have a negative impact ; I *am* using async controllers
- upgrading to glimpse v2 is not a solution for me because it appears it's currently in beta and only targets asp.net 5
- someone proposed [upgrading RazorEngine](https://github.com/Antaris/RazorEngine/issues/268#issuecomment-91625809), so I tried latest version 3.7.5, but that didn't fix the issue

Any idea what workaround could work? Thanks in advance.

**Comment by avanderhoorn** [comment]
Unfortunately there isn't much I can do at the moment. That said, the progress is being tracked at #226
