### ISSUE TITLE
Assembly Signing

### ISSUE THREAD

**Issue by KamyarP** [Glimpse/Glimpse#943]
I Have just tried out glimpse and am very grateful for having these cool features all for free.
However, I was a bit surprised to find out glimpse.autofac and glimpse.core are not signed (Our solution's projects are signed which I think is a very standard thing to do) and I cannot use them unless I rebuild all the related dlls with a key.
Is there any plan to release signed assemblies so I can simply just use nuget to get them?

**Comment by nikmd23** [comment]
We don't currently have plans to sign the assemblies.

I would encourage you to either use one of the "auto-signing" tools that are out there, or building and signing Glimpse from source.
