### ISSUE TITLE
Popup sections need scrollbar on overflow

### ISSUE THREAD

**Issue by mwoffenden** [Glimpse/Glimpse#944]
The Host popup section in particular needs a scrollbar on overflow, otherwise some items are off the bottom of the screen and can't be accessed.

The following CSS seems to fix it for me.  

.glimpse-open .glimpse-hud-popup {
    overflow-y: scroll;
}

**Comment by avanderhoorn** [comment]
Unfortunately there isn't much I can do at the moment. That said, the progress is being tracked at #226
