### ISSUE TITLE
Site Does not Work after Truning Glimpse on

### ISSUE THREAD

**Issue by usefulBee** [Glimpse/Glimpse#946]
That is kind of a very disappointing result for a first timer like me. 
- hit F5 to start the mvc application
- land on the homepage just fine
- navigate to http://localhost:49457/glimpse.axd and every thing look exciting
- turn Glimpse on and the excitement level is getting higher
- try to navigate to the home page or any other page, hit back etc and viola! the disappointment begins:
in IE, I get "Page cannot be displayed" error while firfox I get "Content Encoding Error"

But regardless, happy new year any way!

**Comment by uncled1023** [comment]
I am getting the same issue.  MVC 5, EF 6 .net 4.5.2

**Comment by usefulBee** [comment]
@uncled1023, what amazes is that Glimpse has a great looking website, and the project is backed by Microsoft, but yet there appears to be a very little support behind it.

**Comment by nikmd23** [comment]
@usefulBee or @uncled1023, can you provide a reproduction for this issue?
