### ISSUE TITLE
Internal Server Error After Uninstalling Glimpse Using NuGet Manager VS 2015

### ISSUE THREAD

**Issue by usefulBee** [Glimpse/Glimpse#947]
Error Details copied below:

HTTP Error 500.22 - Internal Server Error

An ASP.NET setting has been detected that does not apply in Integrated managed pipeline mode.

Most likely causes:
•This application defines configuration in the system.web/httpModules section.

Things you can try:
•Migrate the configuration to the system.webServer/modules section. You can do so manually or by using AppCmd from the command line. For example, from the IIS Express install directory, run appcmd migrate config "Default Web Site/". Using AppCmd to migrate your application will enable it to work in Integrated mode. It will continue to work in Classic mode and on previous versions of IIS.
•If you are certain that it is OK to ignore this error, it can be disabled by setting system.webServer/validation@validateIntegratedModeConfiguration to false.
•Alternatively, switch the application to a Classic mode application pool. For example, from the IIS Express install directory, run appcmd set app "Default Web Site/" /applicationPool:"Clr4ClassicAppPool". Only do this if you are unable to migrate your application.

Detailed Error Information:
Module
   ConfigurationValidationModule 

Notification
   BeginRequest 

Handler
   ExtensionlessUrlHandler-Integrated-4.0 

Error Code
   0x80070032 

Requested URL
   http://localhost:49457/ 

Physical Path

Logon Method
   Not yet determined 

Logon User
   Not yet determined 

Request Tracing Directory

More Information:
Integrated mode is the preferred mode for running ASP.NET applications on IIS 7.0 and above. 
View more information »

**Comment by usefulBee** [comment]
The only thing that saved me so far was SourceControl by issuing an "Undo Pending Changes" command

**Comment by itaroiu** [comment]
Is there any solution to this issue? I have the same problem after Glimpse uninstall! Thanks!
