### ISSUE TITLE
Web Forms Package install using Visual Basic

### ISSUE THREAD

**Issue by bnordstrom** [Glimpse/Glimpse#952]
When I installed the web form package (PM> Install-Package Glimpse.WebForms) into a 4.0 visual basic web forms site, it creates the file ~/App_Code/GlimpseSecurityPolicy.cs.  This conflicts with existing VB files and generates a build error along the lines of:

The files '/MySite/App_Code/GlimpseSecurityPolicy.cs' and '/MySite/App_Code/SomeVBFile.vb' use a different language, which is not allowed since they need to be compiled together.

Removing the GlimpseSecurityPolicy.cs file or converting it to VB corrects the issue.  Just a minor annoyance when you install or upgrade the package.

Thanks for the library.

Brian.

**Comment by nikmd23** [comment]
Hey @bnordstrom,

Thanks for telling us about this. I wish there was a way in NuGet to have it include a `.vb` or `.cs` file based on the user's setting, but unfortunately, there isn't.

Please stick with your workaround for now.
