### ISSUE TITLE
Glimpse ADO.NET and sqlserver.managment.SMO objects

### ISSUE THREAD

**Issue by Tarig0** [Glimpse/Glimpse#954]
Hey guys been using this gem of a diagnostic tool and I have found that there is no canned way to create a Glimpse Connection that derives from a non genric connection type.

This causes problems when I want to be able to track what queries are running against my DB when I use the SMO objects found in the SDK for SQL Server client tools. The internal classes can only store a sqlclient.sqlconnection so I can't wrap the connection object.

Would the ability to take a dbconnection and subscribe to its events be able to be implemented be able to be implemented or i there a work around I can use.

**Comment by avanderhoorn** [comment]
Not sure there is any way we can work around this one :(
