### ISSUE TITLE
Auto-format SQL in the SQL tab (command column)

### ISSUE THREAD

**Issue by lukemcgregor** [Glimpse/Glimpse#958]
I use postgres and EF, it doesn't format the actual command sent to SQL which makes it really hard to read in the SQL tab.

It would be really nice to run this through a formatter before displaying the SQL inside glimpse. Something like https://www.nuget.org/packages/PoorMansTSQLFormatter/ might be a good option.

It would probably also need a toggle on/off.

**Comment by avanderhoorn** [comment]
Great idea, tracking on #226
