### ISSUE TITLE
The type 'Newtonsoft.Json.JsonConvert' exists in both 'Glimpse.Core.dll' and 'Newtonsoft.Json.dll'	

### ISSUE THREAD

**Issue by grynek2** [Glimpse/Glimpse#962]
Issue with Ilmerged Newtonsoft libraries. 

Can you use /Internalize switch when combining the libraries so they're not visible outside Glimpse?
I guess this would fix issues  like :The type 'Newtonsoft.Json.JsonConvert' exists in both 'Glimpse.Core.dll' and 'Newtonsoft.Json.dll'

**Comment by sirajmansour-infotrack** [comment]
Any news on this one ??

**Comment by yigitgursoy** [comment]
This is not acceptable.

**Comment by avanderhoorn** [comment]
Only thing I can put forward atm is that you could do a manual build of Glimpse from source and not do the ILmerge step?

**Comment by Spongman** [comment]
i had to uninstall glimpse because of this. why do this? isn't this what nuget is for?

**Comment by olcay** [comment]
Welcome to the club @Spongman 
I really like Glimpse and even did a presentation about it at a company I was working before.
In the end, we removed it from all of our projects because of this issue.
