### ISSUE TITLE
Glimpse Nuget package for asp.net core 1.0

### ISSUE THREAD

**Issue by inongogo** [Glimpse/Glimpse#963]
I have an issue with the Glimpse Nuget package which has nothing to do with your solution but I wonder if you might have encountered it.

When I look at the Glimpse package under %USERPROFILE%\.dnx\packages\Glimpse\2.0.0-beta1\lib\dnx451 or dnxcore50 folder there is no file "Glimpse.Core.dll". There is, however, a file called "_._" which is zero bytes.

When I look in the net45 or net40 or net35 folders there is a file called "Glimpse.Core.dll".

This is also the case when I download the file explicitly from nuget.org (via the download link at https://www.nuget.org/packages/Glimpse/2.0.0-beta1

The error I get when I run the applications is I get the exception ReflectionTypeLoadException when the app executes `app.AddGlimpse()`
The problem is that it's looking for Glimpse.Core, Version=1.8.0.0, Culture=neutral, PublicKeyToken=null

Am I doing something wrong or is the package corrupt?

**Comment by avanderhoorn** [comment]
The `.` package is by design and unlikely to be the (we are taking advantage of a seldom used nuget feature there). Do you have any more information about the exception and what version of dnx you are using?

**Comment by inongogo** [comment]
Thanks for a quick response!

It for taking up your time. It was completely my fault. I used the Serilog.Sinks.Glimpse assembly, version 1.5.14 and it was using the 1.8 version of Glimpse which messed up everything.

Again, I'm sorry!
