### ISSUE TITLE
 Multiple controls with the same ID

### ISSUE THREAD

**Issue by sprice88** [Glimpse/Glimpse#965]
Web Forms Project, where Controls are dynamically added to contentplaceholder. Once I install Glimpse I receive the following. Turning off Glimpse fixes the error.

[HttpException (0x80004005): Multiple controls with the same ID 'ctl00$cphScripts$_jsDiv' were found. Trace requires that controls have unique IDs.]
   System.Web.TraceContext.AddNewControl(String id, String parentId, String type, Int32 viewStateSize, Int32 controlStateSize) +657
   System.Web.UI.Control.BuildProfileTree(String parentId, Boolean calcViewState) +354
   System.Web.UI.Control.BuildProfileTree(String parentId, Boolean calcViewState) +436
   System.Web.UI.Control.BuildProfileTree(String parentId, Boolean calcViewState) +436
   System.Web.UI.Control.BuildProfileTree(String parentId, Boolean calcViewState) +436
   System.Web.UI.Page.BuildPageProfileTree(Boolean enableViewState) +59
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +8157

**Comment by avanderhoorn** [comment]
At the moment there isn't much that we can do. If you want to take a look at the source and see if you can spot the issue and what sort of fix we could do feel free.
