### ISSUE TITLE
Glimpse on Mono

### ISSUE THREAD

**Issue by mistressofjellyfish** [Glimpse/Glimpse#969]
Not exactly an Issue, but I didn't know where I should post this.

So, apparently, Glimpse works finde on Mono:
![Proof](http://hacked.xyz/glimpse.png)

... with one little caveat: on MVC5, you have to add the following line into your RouteConfig.cs:
`routes.IgnoreRoute("glimpse.axd");`

That, dear friends, is totally freakin awesome. Maybe we should run all the Unit tests on a recent mono too.

Glimpse Version: 1.8.6.0
Project Type: ASP.net MVC5
Host:

    $ uname -a
    Linux gasch 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux
    $ mono --version
    Mono JIT compiler version 4.2.2 (Stable 4.2.2.30/996df3c Sun Jan 31 11:58:08 UTC 2016)
    Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
    	TLS:           __thread
    	SIGSEGV:       altstack
    	Notifications: epoll
    	Architecture:  amd64
    	Disabled:      none
    	Misc:          softdebug 
    	LLVM:          supported, not enabled.
    	GC:            sgen
    $ xsp4 --version
    xsp4.exe 3.0.0.0
    Copyright (C) 2002-2011 Novell, Inc.
    Minimalistic web server for testing System.Web

**Comment by nikmd23** [comment]
That is awesome! Last we looked into Mono the real deal breaker was Castle Dynamic Proxy (one of our dependencies) not running there. 

This is great to know - thanks for passing it on!
