### ISSUE TITLE
An unhandled exception of type 'System.StackOverflowException' occurred in Glimpse.Core.dll

### ISSUE THREAD

**Issue by arame3333** [Glimpse/Glimpse#971]
I was asked to fix a bug in a legacy MVC application recently. I found that before I could even try to fix the bug I was getting a StackOverflow exception being thrown.
This exception does not exist in production.
I copied the exception to clipboard and I got the message
An unhandled exception of type 'System.StackOverflowException' occurred in Glimpse.Core.dll

So I Uninstalled Glimpse.MVC4 and Glimpse.EF5 and I no longer have the bug. This is the second time I have had to do this recently. Why is this?

**Comment by nikmd23** [comment]
I'm sorry you're having an issue @arame3333.

Do you have a reproduction we could use?

**Comment by avanderhoorn** [comment]
Closing for the moment until we hear more
