### ISSUE TITLE
MVC controller/action not displaying in Host view

### ISSUE THREAD

**Issue by davidkeaveny** [Glimpse/Glimpse#975]
I have a large web application which is a mix of WebForms and MVC 5. Some of the MVC code uses areas, some of it doesn't. Regardless, when I view an MVC page, the controller/actions are not identified in the Host view, whether Trivial or Detailed. Instead, it shows null/null.

If I expand the Glimpse panel and look at the Execution tab, nothing is shown; however, if I look at the Routes tab, then the routing table is displayed and the correct route is highlighted, so _something_ at least is working. The same for the Views tab - it correctly identifies the views and view engines in use.

**Comment by nikmd23** [comment]
Hi @davidkeaveny, are you able to provide a reproduction of this issue?

**Comment by avanderhoorn** [comment]
Closing till we hear more
