### ISSUE TITLE
UseGlimpse not recongnized in ASP.NET Core RC2

### ISSUE THREAD

**Issue by mdmoura** [Glimpse/Glimpse#976]
I am using Glimpse 2.0 Beta 1 with ASP.NET Core RC2 and the UseGlimpse extension is not recongnized in:

    applicationBuilder.UseGlimple();

I have:

    using Glimpse;

Any idea why?

**Comment by rpaschoal** [comment]
Hello,

Try adding this on "ConfigureServices":

services.AddGlimpse();

Cheers.

**Comment by mdmoura** [comment]
@rpaschoal If I add Glimpse to services I get the error:

    System.TypeLoadException
    Could not load type 'Microsoft.Extensions.PlatformAbstractions.ILibraryManager' from assembly 'Microsoft.Extensions.PlatformAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

And I am not able to add UseGlimpse because it is not recognized.

I think there might be a problem with Glimpse 2.0 Beta 1 and ASP.NET Core RC2.

I had this working with ASP.NET Core RC1. Have you tried it with RC2?

**Comment by nico357** [comment]
Yes I have the same problem!!
with Glimpse 2.0 Beta 1 and ASP.NET Core RC2.

**Comment by YZahringer** [comment]
Same problem...

**Comment by code1line** [comment]
I think we have to wait until Glimpse 2.0 Beta 2...

**Comment by YZahringer** [comment]
https://github.com/Glimpse/Glimpse.Prototype/issues/123

**Comment by mdmoura** [comment]
Any ETA for beta 2?

**Comment by shanselman** [comment]
Ping @avanderhoorn this is taking a little too long ;)

**Comment by mdmoura** [comment]
@shanselman: maybe they are waiting for ASP. NET Core RTM due at the end of June?  :-)

**Comment by nikmd23** [comment]
We are in fact working on RTM support right now. 😄 

There's another issue tracking this very thing over at https://github.com/Glimpse/Glimpse.Prototype/issues/123, so I'm going to close this issue in favor of that one.
