### ISSUE TITLE
How to get to actual view engine type when Glimpse installed?

### ISSUE THREAD

**Issue by valdisiljuconoks** [Glimpse/Glimpse#994]
Hi,

We do have a plugin that enlists all view locations registered within the project (code fragment [here](https://github.com/episerver/DeveloperTools/blob/master/DeveloperTools/Controllers/ViewEngineLocationsController.cs#L16)).

We are asking `ViewEngines.Engines` collection to get back list of `VirtualPathProviderViewEngine`. We need to get into `engine.ViewLocationFormats` and `engine.PartialViewLocationFormats` fields to enlist registered view locations.

As with Glimpse installed, we get back only proxies from `ViewEngines.Engines` and cast yields no results of course.

What would be the best approach here?

Thx guys!

**Comment by nikmd23** [comment]
Hi @valdisiljuconoks!

Unfortunately, once Glimpse has wrapped the `ViewEngine`, there's no way to get back anything but an `IViewEngine`. 

You could disable that feature of Glimpse in your `web.config` with code something like this:

```xml
<glimpse defaultRuntimePolicy="On" endpointBaseUri="~/Glimpse.axd">
    <inspectors>
        <ignoredTypes>
            <add type="Glimpse.Mvc.Inspector.ViewEngineInspector, Glimpse.Mvc3" />
        </ignoredTypes>
    </inspectors>
</glimpse>
```

This might not be the exact right code snippet for your project, but if you go to `/Glimpse.axd`, click on More Details, and uncheck the View Engine Inspector, the exact config code you need will be generated and shown to you.
